In [690]:
from pathlib import Path

data_path = Path(r"C:\Users\Shivshankar_RaviMala\python_code\customer_360_data_quality\data")


In [691]:
for file in data_path.iterdir():   #this is help to itrate all the file from a floder
    print(file.name)

clickstream_500k_events.csv
crm_50000_customers_dirty_v3.csv
orders_300k_dirty.csv
product_catalog_dirty_30pct.csv
support_tickets_30000_dirty.csv


In [692]:
# Importing our first customer master data.

import pandas as pd

# 1. Define the base directory path
data_dir = Path(r"C:\Users\Shivshankar_RaviMala\python_code\customer_360_data_quality\data")


In [693]:
# 2. Add the file name using the / operator
file_path = data_dir / "crm_50000_customers_dirty_v3.csv"

# 3. Reading into the pandas
crm = pd.read_csv(file_path)

In [694]:
crm.head()

,customer_id,first_name,last_name,email,phone_number,gender,dob,signup_date,address,city,state,country,device_id(s),source
0,0d244537-8164-4b84-bcf2-0e43766f3221,mARIA,day,maria.day697@hotmail.com,449.977.1729x282,M,1988-04-11,2016-12-05,107 Joseph Station,Padillaborough,Oregon,Micronesia,56f3a452-b3f5-488b-b90d-8cb2b3343c70;3ab7d21b-...,referral
1,66c5800b-ad5c-4fac-86df-16472d82f02d,KKeevvin,Cantu,kevin.cantu968@gmail.com,501.347.4824x64633,M,1955-09-19,2024-02-03,3577 Anita Knoll Apt. 107,Justinton,Delaware,Portugal,cd83e240-0d50-4e67-b146-23deb6c49940,referral
2,e7852eee-0a28-46dc-aa34-445a02530746,Ronald,Daniel,ronald.daniel138@yahoo.com,+1-268-822-6332x26814,M,1971-11-02,2016-04-12,3440 Tammy Views Suite 698,New Autumnland,Mississippi,Uganda,369b8950-dfae-44ce-bbb4-d292f118be67,web
3,14f0e67d-e60e-4989-88cf-5be50d515a69,Katherine,Smith,katherine.smith357@yahoo.com,864-894-1347,F,1955-03-25,2019-06-21,98888 Morales Lakes,New Jose,Minnesota,Bahrain,3e83071f-53ed-4a05-9dfd-5ff2031443b5,web
4,1ce2f061-345c-4121-a4ba-32963cf9a15d,Brandon,Glover,brandon.glover804@hotmail.com,489.732.5436,M,1968-06-25,2022-01-09,55037 Denise Crest Apt. 565,Port Amber,Oregon,Latvia,751d4410-3d73-4f4c-b432-10a0213b925f,referral


In [695]:
crm.shape # we have 50000 rows and 14 columns 

(50000, 14)

In [696]:
crm.columns

Index(['customer_id', 'first_name', 'last_name', 'email', 'phone_number',
       'gender', 'dob', 'signup_date', 'address', 'city', 'state', 'country',
       'device_id(s)', 'source'],
      dtype='str')

In [697]:
crm.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   50000 non-null  str  
 1   first_name    50000 non-null  str  
 2   last_name     50000 non-null  str  
 3   email         48960 non-null  str  
 4   phone_number  50000 non-null  str  
 5   gender        50000 non-null  str  
 6   dob           50000 non-null  str  
 7   signup_date   50000 non-null  str  
 8   address       50000 non-null  str  
 9   city          50000 non-null  str  
 10  state         50000 non-null  str  
 11  country       50000 non-null  str  
 12  device_id(s)  50000 non-null  str  
 13  source        50000 non-null  str  
dtypes: str(14)
memory usage: 5.3 MB


In [698]:
crm.describe(include = "all") # gives a complete statistical summary of your entire datase

,customer_id,first_name,last_name,email,phone_number,gender,dob,signup_date,address,city,state,country,device_id(s),source
count,50000,50000,50000,48960,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000
unique,48200,5429,7228,46363,46777,3,17733,4383,48200,24534,50,243,48200,3
top,e258ce9d-e577-4c87-886c-4026d73219e6,Michael,Smith,shared1549@gmail.com,586-049-5136,F,1988-06-10,2017-01-06,705 Monique Well Apt. 322,South Michael,Vermont,Korea,df987435-1583-423c-8646-d922a91a45f2,referral
freq,4,818,793,10,9,23333,12,25,4,45,1051,416,4,16768


### General Observations of the Dataset

1. **Total Records:** 50,000 records across 14 attributes.
2. **Missing Emails:** 50,000 - 48,960 = 1,040 (Missing % = 2.08%)
3. **Data Types:** All attributes are stored as strings.



# Part 3 — Hands-on Enterprise Data Profiling

## Exercise 1 — Structural Profiling

Structural profiling establishes the physical structure of the CRM dataset before we investigate the quality of individual attributes.

The objective is to understand:

- Dataset size
- Number of attributes
- Column names
- Data types
- Null/non-null structure
- Overall schema characteristics

The raw dataset is preserved unchanged during profiling.

## Investigation 1 — Dataset Shape

### Objective

Determine the size of the CRM dataset and establish the profiling population and attribute scope.

In [699]:
crm.shape

(50000, 14)

### Observation

The CRM dataset contains 50,000 records and 14 attributes.

The 50,000 records represent the current profiling population, while the 14 attributes define the scope of the structural assessment.

This is a profiling observation only and does not indicate whether the data is good or bad.

## Investigation 2 — Column Names

### Objective

Identify all attributes present in the CRM dataset and establish the schema currently exposed by the source extract.

In [700]:
crm.columns

Index(['customer_id', 'first_name', 'last_name', 'email', 'phone_number',
       'gender', 'dob', 'signup_date', 'address', 'city', 'state', 'country',
       'device_id(s)', 'source'],
      dtype='str')

### Observation 

The CRM dataset contains 14 attributes and which containing all the personal information related to customers.

## Investigation 3 — Data Types

### Objective

Determine how pandas has interpreted each attribute and assess whether the inferred data types appear appropriate for their intended business meaning.

In [701]:
crm.dtypes

customer_id     str
first_name      str
last_name       str
email           str
phone_number    str
gender          str
dob             str
signup_date     str
address         str
city            str
state           str
country         str
device_id(s)    str
source          str
dtype: object

### Observations

All 14 attributes are currently represented as string/object-like data. This is a structural observation. Some attributes, such as dates, may require further type validation because their physical representation does not necessarily reflect their intended business type.

## Investigation 4 — Dataset Structure and Non-Null Counts

### Objective

Use the dataset metadata to examine column structure, data types, non-null population, and memory usage.

In [702]:
crm.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   50000 non-null  str  
 1   first_name    50000 non-null  str  
 2   last_name     50000 non-null  str  
 3   email         48960 non-null  str  
 4   phone_number  50000 non-null  str  
 5   gender        50000 non-null  str  
 6   dob           50000 non-null  str  
 7   signup_date   50000 non-null  str  
 8   address       50000 non-null  str  
 9   city          50000 non-null  str  
 10  state         50000 non-null  str  
 11  country       50000 non-null  str  
 12  device_id(s)  50000 non-null  str  
 13  source        50000 non-null  str  
dtypes: str(14)
memory usage: 5.3 MB


### observations

The Important Observation, in the email not_null count we have around 48960 out of 50000 records.
1,040 (Missing values) in the email attribute.

## Investigation 5 — Initial Missing-Value Structure

### Objective

Identify the number and percentage of pandas-recognized NULL values in each attribute.

This is an initial completeness observation. A NULL value is not automatically a Data Quality defect; whether it is a defect depends on the business requirement for the attribute.

In [703]:
crm.isnull().sum()

customer_id        0
first_name         0
last_name          0
email           1040
phone_number       0
gender             0
dob                0
signup_date        0
address            0
city               0
state              0
country            0
device_id(s)       0
source             0
dtype: int64

In [704]:
crm.isnull().mean() * 100

customer_id     0.00
first_name      0.00
last_name       0.00
email           2.08
phone_number    0.00
gender          0.00
dob             0.00
signup_date     0.00
address         0.00
city            0.00
state           0.00
country         0.00
device_id(s)    0.00
source          0.00
dtype: float64

### Observation 

Around 2.08% of the values in the email has null (1040 Missing values).

# Exercise 2 — High-Level Content Profiling

## Investigation 1 — Descriptive Profile

### Objective

Establish an initial understanding of the values contained within each attribute.

For string attributes, `describe(include="all")` provides metrics such as:

- count
- unique
- top
- frequency

These metrics are used to identify attributes that require deeper investigation. They are observations rather than confirmed Data Quality defects.

In [1102]:
crm.describe(include = "all")

,customer_id,first_name,last_name,email,phone_number,gender,dob,signup_date,address,city,state,country,device_id(s),source
count,50000,50000,50000,48960,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000
unique,48200,5429,7228,46363,46777,3,17733,4383,48200,24534,50,243,48200,3
top,e258ce9d-e577-4c87-886c-4026d73219e6,Michael,Smith,shared1549@gmail.com,586-049-5136,F,1988-06-10,2017-01-06,705 Monique Well Apt. 322,South Michael,Vermont,Korea,df987435-1583-423c-8646-d922a91a45f2,referral
freq,4,818,793,10,9,23333,12,25,4,45,1051,416,4,16768


### Observation

The `describe(include="all")` profile provides an initial view of the value distribution and cardinality of the CRM attributes.

Key observations:

- The dataset contains 50,000 records.
- Most attributes have a `count` of 50,000, indicating that pandas does not identify NULL values in those columns.
- The `email` attribute has a count of 48,960, indicating 1,040 NULL values.
- `customer_id` has 48,200 unique values across 50,000 records, indicating that some customer IDs occur more than once.
- `gender` has only 3 unique values, while `state` has 50 unique values and `country` has 243 unique values, showing different levels of cardinality across attributes.
- `first_name`, `last_name`, `email`, `phone_number`, `dob`, and `city` contain substantially more unique values, indicating higher cardinality.
- The `top` and `freq` statistics identify the most frequently occurring value in each attribute and its frequency.

These are high-level profiling observations. They do not yet establish that a Data Quality issue exists. Further column-level profiling and business-rule validation are required to determine whether repeated values, NULLs, or unusual cardinality represent actual Data Quality risks.

## Exercise 3 — Column-Level Profiling

### Column: `customer_id`

#### Business Context

`customer_id` is the identifier used to identify a customer within the CRM dataset.

#### Profiling Objective

Assess the completeness, uniqueness, and validity characteristics of the `customer_id` attribute.

---

### Investigation 1 — Completeness

#### Objective

Determine whether any `customer_id` values are missing.

#### Profiling Question

Are all CRM records populated with a customer identifier?

#### Python

In [1103]:
crm['customer_id'].isna().sum() 

np.int64(0)

In [1104]:
crm['customer_id'].isna().mean() * 100

np.float64(0.0)

### Observation

The `customer_id` attribute contains 0 NULL values across the 50,000-record profiling population, resulting in a NULL rate of 0.0%.

This indicates that all records have a non-NULL value populated in the `customer_id` attribute.

### DQ Interpretation

From a NULL-based completeness perspective, no missing-value issue was identified for `customer_id`.

However, a non-NULL value does not necessarily mean that the customer identifier is complete or valid. Values such as empty strings, whitespace, placeholder values, or malformed identifiers may still require further investigation.

Therefore, the completeness assessment will be followed by uniqueness and validity profiling.

### Investigation 2 — Measure Distinctness

#### Objective

Determine the number of distinct `customer_id` values in the CRM dataset and compare it with the total profiling population.

This helps us understand the degree of value repetition within the `customer_id` attribute and provides an initial indication of whether further uniqueness investigation is required.

In [1105]:
crm["customer_id"].nunique()

48200

In [1106]:
crm["customer_id"].nunique() / len(crm) * 100

96.39999999999999

### Observation

The `customer_id` attribute contains 48,200 distinct values across 50,000 records, resulting in a distinctness rate of 96.4%.

This indicates that some `customer_id` values are repeated and require further uniqueness investigation.

### Investigation 3 — Identify Which IDs Repeat

#### Objective

Identify the specific `customer_id` values that occur more than once in the CRM dataset.

This will allow us to determine which identifiers are repeated and quantify the extent of repetition before assessing whether they represent a Data Quality issue.

In [1107]:
duplicate_ids = crm["customer_id"].value_counts()

In [1108]:
duplicate_ids[duplicate_ids > 1].head(10)

customer_id
e258ce9d-e577-4c87-886c-4026d73219e6    4
1ce2f061-345c-4121-a4ba-32963cf9a15d    3
f9b8fa4a-aba8-4e4a-9d8b-37ce7c2197bc    3
d4783bab-5a16-42c3-bca1-3f5c6eff80b9    3
6dc393a8-d1bd-4130-b114-dc2761607e5d    3
cd65d27b-32da-433b-8683-294c3158ce85    3
81a28cc0-22a6-46df-a45a-962fc04e033a    3
663ea09b-0231-4c3a-9965-6b1a0a1f3b07    3
e11ddca5-90da-4e79-bb77-83affde11bc3    3
bfd3ec45-c8c0-415e-8d71-b06f6b5efc0a    3
Name: count, dtype: int64

### Observation

The profiling identifies repeated `customer_id` values in the CRM dataset. Among the displayed results, one ID occurs 4 times, while the other four IDs each occur 3 times.

This confirms that some customer identifiers are repeated and warrants further investigation into the extent and nature of these repetitions.

### Investigation 4 - Count the Number of Duplicates ID's

- The Previous output tells us which ID's duplicated?


In [1109]:
duplicate_ids[duplicate_ids > 1].count()

np.int64(1734)

### Observation

The profiling identifies repeated `customer_id` values in the CRM dataset. The displayed results show that one customer ID occurs 4 times, while four other customer IDs each occur 3 times.

This confirms that some `customer_id` values are repeated. However, repeated identifier values do not by themselves confirm duplicate customer records or a Data Quality defect.

Further profiling is required to quantify the total number of repeated IDs and affected records.

### Step 5 — Count the Records Involved

#### Objective

Determine the total number of CRM records associated with `customer_id` values that occur more than once.

This measures the number of records affected by repeated customer identifiers, complementing the count of distinct repeated IDs identified in the previous investigation.

In [1110]:
duplicate_ids[duplicate_ids > 1].sum()

np.int64(3534)

### Observation

A total of 3,534 CRM records are associated with `customer_id` values that occur more than once.

This means that 3,534 out of the 50,000 CRM records are affected by repeated customer identifiers, representing approximately 7.07% of the profiling population.

This is a uniqueness observation and does not yet confirm that these records are duplicate customer records or a Data Quality defect. Further investigation is required to determine whether the repeated IDs represent legitimate multiple records or duplicate/conflicting customer records.

### Step 6 — Isolate Records with Repeated Customer IDs

#### Objective

Create a subset of the CRM dataset containing all records associated with `customer_id` values that occur more than once.

This allows us to inspect the affected records directly and determine whether the repeated identifiers represent actual duplicate customer records or legitimate multiple records.

In [1111]:
duplicated_customer_records = crm[
    crm["customer_id"].isin(
        duplicate_ids[duplicate_ids > 1].index
    )
]

duplicated_customer_records.sort_values("customer_id").head(10)

,customer_id,first_name,last_name,email,phone_number,gender,dob,signup_date,address,city,state,country,device_id(s),source
1393,005a7521-db6a-406e-b14e-97bf259f96fb,Alexandra,Ellison,alexandra.ellison003@yahoo.com,(543)768-3047x8198,M,2005-06-09,2018-04-29,427 Walton Canyon,Jamiechester,Arkansas,France,14edf41b-5067-45da-834f-7318116cc466,referral
5785,005a7521-db6a-406e-b14e-97bf259f96fb,Alexandra,Ellison,alexandra.ellison003@yahoo.com,(543)768-3047x8198,M,2005-06-09,2018-04-29,427 Walton Canyon,Jamiechester,Arkansas,France,14edf41b-5067-45da-834f-7318116cc466,referral
30391,00682ed4-54ac-434e-b800-a4dfa3775f10,Melissa,Peck,shared1349@hotmail.com,6610153591,M,2001-01-19,2024-11-20,893 Chavez Landing Suite 262,New Carrieville,Hawaii,Serbia,002db8ff-ed9f-48ed-ac1b-9f977421bc66,app
38030,00682ed4-54ac-434e-b800-a4dfa3775f10,Melissa,PECK,shared1349@hotmail.com,6610153591,M,2001-01-19,2024-11-20,893 Chavez Landing Suite 262,New Carrieville,Hawaii,Serbia,002db8ff-ed9f-48ed-ac1b-9f977421bc66,app
17061,0070c246-7754-46db-a55f-b14188840068,JOSEPH,sMITH,joseph.smith734@hotmail.com,001-740-556-0991,F,1996-05-10,2021-05-15,2067 Allen Ways,New Patricia,Louisiana,Palau,c33a812d-fb6d-485e-be77-fc0e1526afeb,web
39917,0070c246-7754-46db-a55f-b14188840068,Joseph,Smith,joseph.smith734@hotmail.com,001-740-556-0991,F,1996-05-10,2021-05-15,2067 Allen Ways,New Patricia,Louisiana,Palau,c33a812d-fb6d-485e-be77-fc0e1526afeb,web
43335,00b15609-c67f-4057-a23e-846120a5a078,John,Paul,john.paul309@yahoo.com,+1-045-245-5744x387,M,1960-01-19,2022-03-22,95225 Davis Passage,Orozcochester,South Carolina,Syrian Arab Republic,1f8da822-3fad-40c4-9c0a-2b9a8adb3325,referral
400,00b15609-c67f-4057-a23e-846120a5a078,John,Paul,john.paul309@yahoo.com,+1-045-245-5744x387,M,1960-01-19,2022-03-22,95225 Davis Passage,Orozcochester,South Carolina,Syrian Arab Republic,1f8da822-3fad-40c4-9c0a-2b9a8adb3325,referral
43939,00c929d1-753c-49a8-af28-eb3ffe0ad087,Tina,Frost,caitlin.richardson319@hotmail.com,(142)446-4128,M,1996-05-01,2016-11-01,531 Michael Fords Suite 310,Lake Michaelberg,Wyoming,Gabon,14c1d235-28f3-4376-ba5c-758f17d67c68,referral
34468,00c929d1-753c-49a8-af28-eb3ffe0ad087,tINA,Frost,caitlin.richardson319@hotmail.com,(142)446-4128,M,1996-05-01,2016-11-01,531 Michael Fords Suite 310,Lake Michaelberg,Wyoming,Gabon,14c1d235-28f3-4376-ba5c-758f17d67c68,referral


### Observation

Inspection of the records associated with repeated `customer_id` values shows evidence of actual duplicate customer records.

The displayed records contain repeated `customer_id` values with identical or near-identical customer attributes, including name, email, phone number, date of birth, address, device ID, and source.

In one example, the records are identical across the displayed attributes. In another, the records differ only in the capitalization of the last name, suggesting a potential formatting inconsistency rather than a different customer.

This provides evidence that the repeated `customer_id` values may represent duplicate customer records. Further profiling is required to quantify how many repeated-ID records are exact duplicates versus records containing conflicting or differing attribute values.

In [1112]:
exact_duplicated_cr_recoreds = duplicated_customer_records[
    duplicated_customer_records.duplicated(keep=False)
]

exact_duplicated_cr_recoreds.sort_values("customer_id").head(10)

,customer_id,first_name,last_name,email,phone_number,gender,dob,signup_date,address,city,state,country,device_id(s),source
1393,005a7521-db6a-406e-b14e-97bf259f96fb,Alexandra,Ellison,alexandra.ellison003@yahoo.com,(543)768-3047x8198,M,2005-06-09,2018-04-29,427 Walton Canyon,Jamiechester,Arkansas,France,14edf41b-5067-45da-834f-7318116cc466,referral
5785,005a7521-db6a-406e-b14e-97bf259f96fb,Alexandra,Ellison,alexandra.ellison003@yahoo.com,(543)768-3047x8198,M,2005-06-09,2018-04-29,427 Walton Canyon,Jamiechester,Arkansas,France,14edf41b-5067-45da-834f-7318116cc466,referral
400,00b15609-c67f-4057-a23e-846120a5a078,John,Paul,john.paul309@yahoo.com,+1-045-245-5744x387,M,1960-01-19,2022-03-22,95225 Davis Passage,Orozcochester,South Carolina,Syrian Arab Republic,1f8da822-3fad-40c4-9c0a-2b9a8adb3325,referral
43335,00b15609-c67f-4057-a23e-846120a5a078,John,Paul,john.paul309@yahoo.com,+1-045-245-5744x387,M,1960-01-19,2022-03-22,95225 Davis Passage,Orozcochester,South Carolina,Syrian Arab Republic,1f8da822-3fad-40c4-9c0a-2b9a8adb3325,referral
17609,00d5aa6f-3b76-40da-90a7-1526ae3211b3,Kelly,Bennett,shared1450@gmail.com,605.131.6162x349,F,1976-09-01,2021-12-05,7015 James Falls,Kristenport,Arizona,Oman,6b05d63b-4d11-4c6d-9e14-770f657c6a39,app
43836,00d5aa6f-3b76-40da-90a7-1526ae3211b3,Kelly,Bennett,shared1450@gmail.com,605.131.6162x349,F,1976-09-01,2021-12-05,7015 James Falls,Kristenport,Arizona,Oman,6b05d63b-4d11-4c6d-9e14-770f657c6a39,app
27020,00d9d551-d21c-4355-a3a6-6a76180194c8,Brad,Jones,brad.jones644@gmail.com,+1-710-203-1409x51948,F,1960-04-19,2020-04-16,302 Taylor Groves Suite 333,South Stephanie,South Carolina,New Zealand,c133b493-008d-4ec2-a934-b13782fbb1e2,app
36079,00d9d551-d21c-4355-a3a6-6a76180194c8,Brad,Jones,brad.jones644@gmail.com,+1-710-203-1409x51948,F,1960-04-19,2020-04-16,302 Taylor Groves Suite 333,South Stephanie,South Carolina,New Zealand,c133b493-008d-4ec2-a934-b13782fbb1e2,app
41230,011ecd43-e9f7-429c-b873-8a4f1ae4b96b,Mary,Rhodes,mary.rhodes599@yahoo.com,217-294-1398,F,2002-07-04,2018-05-06,2479 Robert Drive Suite 425,New Rodneyshire,Missouri,Nicaragua,3aab6405-b9dd-4e9d-b5f7-b50bda04d256,referral
47769,011ecd43-e9f7-429c-b873-8a4f1ae4b96b,Mary,Rhodes,mary.rhodes599@yahoo.com,217-294-1398,F,2002-07-04,2018-05-06,2479 Robert Drive Suite 425,New Rodneyshire,Missouri,Nicaragua,3aab6405-b9dd-4e9d-b5f7-b50bda04d256,referral


In [1113]:
duplicated_customer_records.duplicated().sum()      # 1021 recores are the exactly matching out of 3,534, need to validate on remaining 2,513 records.

np.int64(1021)

## Duplicate Customer ID Investigation Flow

**3,534 records associated with repeated `customer_id`s**

⬇️

├── **1,021 exact duplicate records**
│   → Already identified
│
└── **2,513 non-exact records**
    → Need further investigation

⬇️

### What differs between the non-exact records?

- **Legitimate variation?**
- **Formatting difference?**
- **Conflicting attributes?**
- **Duplicate customer?**
- **Source-system issue?**


### Remaining 2,513 Records — Investigation Scenarios

The remaining records may represent two scenarios:

1. **Same `customer_id`, different records**  
   → Same ID appears with different attribute values.

2. **Different `customer_id`, potentially same customer**  
   → Different IDs may represent the same real-world customer.

In [1114]:
non_exact_duplicated_cr_recoreds = duplicated_customer_records[
    duplicated_customer_records.duplicated(keep = False) == False
]

len(non_exact_duplicated_cr_recoreds)

1521

In [1115]:
duplicated_customer_records.shape

(3534, 14)

In [1116]:
exact_duplicated_cr_recoreds.shape

(2013, 14)

In [1117]:
non_exact_duplicated_cr_recoreds.shape

(1521, 14)

In [1118]:
non_exact_duplicated_cr_recoreds['customer_id'].nunique()  # tells No of customer IDs are distinct out of 2,513 records.

768

In [1119]:
non_exact_duplicated_cr_recoreds.groupby("customer_id").size().sort_values(ascending = False).head(20)  # tells the customer IDs which are repeated in the non-exact duplicated records.

customer_id
6bf6358c-5c2f-4b5d-ae9b-3bfe4b9af0f4    3
7828b977-5ddf-4f5f-87f1-54a63003813d    3
6dc393a8-d1bd-4130-b114-dc2761607e5d    3
7eef8095-162a-4cf2-b792-e656618cec52    3
8c6c5a10-279a-4cee-a40f-a4689489728a    3
9d7dd3c5-9ca6-4248-9c5d-4360118aa0ce    3
d0c7ecce-8d2c-49e9-bc84-696b869cc207    3
deafb728-fe01-4c6f-acd6-fccdfb6ff331    3
e11ddca5-90da-4e79-bb77-83affde11bc3    3
e6a32e73-48ff-41df-8d01-2e3847f65692    3
f5962450-ac58-4eaa-88a4-804851e5344f    3
00c929d1-753c-49a8-af28-eb3ffe0ad087    2
0167fd2f-c24d-4f99-a133-6678590ae380    2
01695a54-eb34-4506-873d-669cc875b8d0    2
01c49ac0-9207-4a30-b5c2-87f76b5ee503    2
02114cd2-1da6-42fe-b8c6-04e7d9922b53    2
0285e90e-e420-4e22-a3fc-a9c4db5a87b1    2
0296267f-4157-4af2-a940-259a366d0b29    2
032f8a68-d58d-4393-9e51-cafd6015023d    2
041958d6-9d04-4872-ae40-3f10570de829    2
dtype: int64

In [1120]:
non_exact_duplicated_cr_recoreds[
    non_exact_duplicated_cr_recoreds["customer_id"] == "6bf6358c-5c2f-4b5d-ae9b-3bfe4b9af0f4"
]

,customer_id,first_name,last_name,email,phone_number,gender,dob,signup_date,address,city,state,country,device_id(s),source
23418,6bf6358c-5c2f-4b5d-ae9b-3bfe4b9af0f4,Bryan,Ba7ker,connie.church526@gmail.com,1107624225,O,2007-01-30,2025-09-10,81475 ALEXANDER VILLE SUITE 474,Meredithshire,West Virginia,Niger,8713dfaf-ac04-4c14-a3ca-6916db82daad,referral
42212,6bf6358c-5c2f-4b5d-ae9b-3bfe4b9af0f4,Bryan,Baker,connie.church526@gmail.com,1107624225,O,2007-01-30,2025-09-10,81475 ALEXANDER VILLE SUITE 474,Meredithshire,West Virginia,Niger,8713dfaf-ac04-4c14-a3ca-6916db82daad,referral
42930,6bf6358c-5c2f-4b5d-ae9b-3bfe4b9af0f4,bryan,BAKER,connie.church526@gmail.com,1107624225,O,2007-01-30,2025-09-10,81475 ALEXANDER VILLE SUITE 474,Meredithshire,West Virginia,Niger,8713dfaf-ac04-4c14-a3ca-6916db82daad,referral


## Investigation — Attribute-Level Conflict Profiling

### Objective

Determine how many distinct values exist for each customer attribute within the 768 customer IDs represented by the 1,521 non-exact records.

This helps identify which attributes are consistent and which contain conflicting values across records sharing the same `customer_id`.


In [1121]:
non_exact_duplicated_cr_recoreds.groupby("customer_id")[
    ["first_name", "last_name", "email", "phone_number"]
].nunique().head(10)

,first_name,last_name,email,phone_number
customer_id,,,,
00682ed4-54ac-434e-b800-a4dfa3775f10,2,2,1,1
0070c246-7754-46db-a55f-b14188840068,2,2,1,1
00c929d1-753c-49a8-af28-eb3ffe0ad087,2,2,1,1
0167fd2f-c24d-4f99-a133-6678590ae380,2,2,1,1
01695a54-eb34-4506-873d-669cc875b8d0,2,2,1,1
01c49ac0-9207-4a30-b5c2-87f76b5ee503,2,2,1,1
02114cd2-1da6-42fe-b8c6-04e7d9922b53,2,2,1,1
0285e90e-e420-4e22-a3fc-a9c4db5a87b1,2,2,1,1
0296267f-4157-4af2-a940-259a366d0b29,2,2,1,1


### Observation

The profiling shows that repeated `customer_id` values have multiple representations for `first_name` and `last_name`, while `email` and `phone_number` are mostly consistent.

This indicates potential attribute-level conflicts that require further investigation.


In [1122]:
attribute_variation = (
    non_exact_duplicated_cr_recoreds
    .groupby("customer_id")[
        [
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "gender",
            "dob",
            "signup_date",
            "address",
            "city",
            "state",
            "country",
            "device_id(s)",
            "source"
        ]
    ]
    .nunique()
)

attribute_variation.head()

,first_name,last_name,email,phone_number,gender,dob,signup_date,address,city,state,country,device_id(s),source
customer_id,,,,,,,,,,,,,
00682ed4-54ac-434e-b800-a4dfa3775f10,2,2,1,1,1,1,1,1,1,1,1,1,1
0070c246-7754-46db-a55f-b14188840068,2,2,1,1,1,1,1,1,1,1,1,1,1
00c929d1-753c-49a8-af28-eb3ffe0ad087,2,2,1,1,1,1,1,1,1,1,1,1,1
0167fd2f-c24d-4f99-a133-6678590ae380,2,2,1,1,1,1,1,1,1,1,1,1,1
01695a54-eb34-4506-873d-669cc875b8d0,2,2,1,1,1,1,1,1,1,1,1,1,1


In [1123]:
attribute_variation.sum().sort_values(ascending=False)

first_name      1510
last_name       1510
phone_number     768
gender           768
dob              768
state            768
signup_date      768
address          768
city             768
device_id(s)     768
country          768
source           768
email            750
dtype: int64

In [1124]:
attribute_variation_pct = ((attribute_variation > 1).mean() * 100).round(2)
attribute_variation_pct

first_name      95.18
last_name       95.18
email            0.00
phone_number     0.00
gender           0.00
dob              0.00
signup_date      0.00
address          0.00
city             0.00
state            0.00
country          0.00
device_id(s)     0.00
source           0.00
dtype: float64

### Observation

Among the repeated `customer_id` groups, `first_name` and `last_name` show variation in **95.18%** of groups, while the other profiled attributes show **0% variation**.

This indicates that the name attributes are the primary source of variation in these records and require further investigation.

### Objective

Identify the number of `customer_id` groups where `first_name` has multiple distinct values, so we can investigate the nature of the name variation.

In [1125]:
first_name_conflict_ids = attribute_variation[
    attribute_variation["first_name"] > 1
].index

len(first_name_conflict_ids)



731

In [1126]:
attribute_variation.head(5)

,first_name,last_name,email,phone_number,gender,dob,signup_date,address,city,state,country,device_id(s),source
customer_id,,,,,,,,,,,,,
00682ed4-54ac-434e-b800-a4dfa3775f10,2,2,1,1,1,1,1,1,1,1,1,1,1
0070c246-7754-46db-a55f-b14188840068,2,2,1,1,1,1,1,1,1,1,1,1,1
00c929d1-753c-49a8-af28-eb3ffe0ad087,2,2,1,1,1,1,1,1,1,1,1,1,1
0167fd2f-c24d-4f99-a133-6678590ae380,2,2,1,1,1,1,1,1,1,1,1,1,1
01695a54-eb34-4506-873d-669cc875b8d0,2,2,1,1,1,1,1,1,1,1,1,1,1


In [1127]:
attribute_variation.loc[
    first_name_conflict_ids,
    "first_name"
].value_counts().sort_index()

first_name
2    720
3     11
Name: count, dtype: int64

In [1128]:
first_name_conflict_ids[:5]

Index(['00682ed4-54ac-434e-b800-a4dfa3775f10',
       '0070c246-7754-46db-a55f-b14188840068',
       '00c929d1-753c-49a8-af28-eb3ffe0ad087',
       '0167fd2f-c24d-4f99-a133-6678590ae380',
       '01695a54-eb34-4506-873d-669cc875b8d0'],
      dtype='str', name='customer_id')

In [1129]:
# 1. sample of customer IDs with name conflict
non_exact_duplicated_cr_recoreds[
    non_exact_duplicated_cr_recoreds['customer_id'] == "00682ed4-54ac-434e-b800-a4dfa3775f10"
][['first_name', 'last_name', 'email']]

,first_name,last_name,email
30391,Melissa,Peck,shared1349@hotmail.com
38030,Melissa,PECK,shared1349@hotmail.com


In [1130]:
# 2. sample of customer IDs with name conflict
non_exact_duplicated_cr_recoreds[
    non_exact_duplicated_cr_recoreds['customer_id'] == "00c929d1-753c-49a8-af28-eb3ffe0ad087"
][['first_name', 'last_name', 'email']]

,first_name,last_name,email
34468,tINA,Frost,caitlin.richardson319@hotmail.com
43939,Tina,Frost,caitlin.richardson319@hotmail.com


In [1131]:
# 3. sample of customer IDs with name conflict
non_exact_duplicated_cr_recoreds[
    non_exact_duplicated_cr_recoreds['customer_id'] == "01695a54-eb34-4506-873d-669cc875b8d0"
][['first_name', 'last_name', 'email']]

,first_name,last_name,email
25598,Sean,Cook2e,sean.cooke027@yahoo.com
26181,Sean,Cooke,sean.cooke027@yahoo.com


### Recovery Note

During exploratory analysis, the derived `customer_id` column was inadvertently overwritten while investigating an individual customer ID.

The raw `crm` DataFrame was verified to remain unchanged. The affected derived population was therefore discarded and recreated directly from `crm`.

Subsequent analysis uses the reconstructed population.

In [1132]:
non_exact_duplicated_cr_recoreds[
    'customer_id'
].value_counts().loc["00682ed4-54ac-434e-b800-a4dfa3775f10"]

np.int64(2)

In [1133]:
(non_exact_duplicated_cr_recoreds['customer_id'] 
 == "00682ed4-54ac-434e-b800-a4dfa3775f10").sum()

np.int64(2)

In [1134]:
non_exact_duplicated_cr_recoreds['customer_id'].head()

20     eba53401-a44b-4ebd-834f-d4b0a059d14c
53     ac2f0eed-0975-4d23-9102-493d7d71fc28
62     26bd5003-c14a-484f-9f19-51fe7aa6e468
118    f1f3745d-81e0-4cad-8798-df0a4a64a2c7
142    f6b91410-1c59-434b-92e8-6758da6701d5
Name: customer_id, dtype: str

In [1135]:
non_exact_duplicated_cr_recoreds.shape

(1521, 14)

In [1136]:
non_exact_duplicated_cr_recoreds["customer_id"].nunique()

768

In [1137]:
non_exact_duplicated_cr_recoreds["customer_id"].value_counts().head(10)

customer_id
6dc393a8-d1bd-4130-b114-dc2761607e5d    3
e11ddca5-90da-4e79-bb77-83affde11bc3    3
7eef8095-162a-4cf2-b792-e656618cec52    3
d0c7ecce-8d2c-49e9-bc84-696b869cc207    3
e6a32e73-48ff-41df-8d01-2e3847f65692    3
deafb728-fe01-4c6f-acd6-fccdfb6ff331    3
8c6c5a10-279a-4cee-a40f-a4689489728a    3
9d7dd3c5-9ca6-4248-9c5d-4360118aa0ce    3
f5962450-ac58-4eaa-88a4-804851e5344f    3
7828b977-5ddf-4f5f-87f1-54a63003813d    3
Name: count, dtype: int64

In [1138]:
crm["customer_id"].nunique()

48200

In [1139]:
crm["customer_id"].value_counts().head()

customer_id
e258ce9d-e577-4c87-886c-4026d73219e6    4
1ce2f061-345c-4121-a4ba-32963cf9a15d    3
f9b8fa4a-aba8-4e4a-9d8b-37ce7c2197bc    3
d4783bab-5a16-42c3-bca1-3f5c6eff80b9    3
6dc393a8-d1bd-4130-b114-dc2761607e5d    3
Name: count, dtype: int64

In [1140]:
duplicate_ids = crm["customer_id"].value_counts()

In [1141]:
duplicated_customer_records = crm[
    crm["customer_id"].isin(
        duplicate_ids[duplicate_ids > 1].index
    )
]

In [1142]:
duplicated_customer_records.count()

customer_id     3534
first_name      3534
last_name       3534
email           3455
phone_number    3534
gender          3534
dob             3534
signup_date     3534
address         3534
city            3534
state           3534
country         3534
device_id(s)    3534
source          3534
dtype: int64

In [1143]:
duplicated_customer_records.count()

customer_id     3534
first_name      3534
last_name       3534
email           3455
phone_number    3534
gender          3534
dob             3534
signup_date     3534
address         3534
city            3534
state           3534
country         3534
device_id(s)    3534
source          3534
dtype: int64

In [1144]:
duplicated_customer_records.shape

(3534, 14)

In [1145]:
exact_duplicated_cr_records = duplicated_customer_records[
    duplicated_customer_records.duplicated(keep=False)
]

exact_duplicated_cr_records.sort_values(by="customer_id").tail(10)

,customer_id,first_name,last_name,email,phone_number,gender,dob,signup_date,address,city,state,country,device_id(s),source
33240,ff68fe03-8500-4e32-830b-a337b0d84d87,Donald,Chen,donald.chen065@yahoo.com,3208460022,F,1959-05-14,2018-06-04,25328 Cannon Green Apt. 464,New Melissa,Colorado,Belgium,5fe358fc-3995-47c6-a51d-a914b4322f19,web
36973,ff68fe03-8500-4e32-830b-a337b0d84d87,Donald,Chen,donald.chen065@yahoo.com,3208460022,F,1959-05-14,2018-06-04,25328 Cannon Green Apt. 464,New Melissa,Colorado,Belgium,5fe358fc-3995-47c6-a51d-a914b4322f19,web
3584,ff69c690-7a61-4daa-9cad-33cdaaccabce,Ryan,Bautista,shared1105@yahoo.com,041.071.4963x4188,O,2003-06-20,2016-02-13,505 Daniel Mill Suite 058,West Billytown,Utah,French Polynesia,d0d42299-8800-46b8-a207-35c55b763670,referral
12441,ff69c690-7a61-4daa-9cad-33cdaaccabce,Ryan,Bautista,shared1105@yahoo.com,041.071.4963x4188,O,2003-06-20,2016-02-13,505 Daniel Mill Suite 058,West Billytown,Utah,French Polynesia,d0d42299-8800-46b8-a207-35c55b763670,referral
13601,ffb1bfd6-438e-461a-90da-643e38ec7de6,Amy,Delgado,amy.delgado987@hotmail.com,(379)102-9660,F,1967-03-21,2016-01-31,332 Stephen Plain Suite 387,Thomasfurt,Utah,Saint Vincent and the Grenadines,35a082e2-3f5b-4a29-916a-235a1fa9a273,app
9676,ffb1bfd6-438e-461a-90da-643e38ec7de6,Amy,Delgado,amy.delgado987@hotmail.com,(379)102-9660,F,1967-03-21,2016-01-31,332 Stephen Plain Suite 387,Thomasfurt,Utah,Saint Vincent and the Grenadines,35a082e2-3f5b-4a29-916a-235a1fa9a273,app
20056,ffcfa884-bce9-4d2f-83ef-63d133f1eaae,Brian,Osborne,brian.osborne433@gmail.com,001-872-338-1051x09337,M,1968-10-31,2014-12-21,4787 Moody Burg Suite 418,Garzafurt,Mississippi,Cape Verde,85f537e2-24a8-41a6-8656-7e990d9d4174,app
13924,ffcfa884-bce9-4d2f-83ef-63d133f1eaae,Brian,Osborne,brian.osborne433@gmail.com,001-872-338-1051x09337,M,1968-10-31,2014-12-21,4787 Moody Burg Suite 418,Garzafurt,Mississippi,Cape Verde,85f537e2-24a8-41a6-8656-7e990d9d4174,app
47910,fffdde56-f0eb-4e19-9007-ecc80643a5c6,Megan,Briggs,ricky.chavez058@hotmail.com,(829)909-7904,M,2005-02-07,2016-06-21,8195 Mcdonald View Suite 543,Millerbury,Utah,Germany,ddfd71cd-6aca-40d8-8550-8d6c01794001;8c29c6bf-...,app
47013,fffdde56-f0eb-4e19-9007-ecc80643a5c6,Megan,Briggs,ricky.chavez058@hotmail.com,(829)909-7904,M,2005-02-07,2016-06-21,8195 Mcdonald View Suite 543,Millerbury,Utah,Germany,ddfd71cd-6aca-40d8-8550-8d6c01794001;8c29c6bf-...,app


In [1146]:
non_exact_duplicated_cr_records = duplicated_customer_records[
    duplicated_customer_records.duplicated(keep=False) == False
]

In [1147]:
non_exact_duplicated_cr_records.shape

(1521, 14)

In [1148]:
non_exact_duplicated_cr_records['customer_id'].nunique()

768

In [1149]:
non_exact_duplicated_cr_records['customer_id'].value_counts().head(10)

customer_id
6dc393a8-d1bd-4130-b114-dc2761607e5d    3
e11ddca5-90da-4e79-bb77-83affde11bc3    3
7eef8095-162a-4cf2-b792-e656618cec52    3
d0c7ecce-8d2c-49e9-bc84-696b869cc207    3
e6a32e73-48ff-41df-8d01-2e3847f65692    3
deafb728-fe01-4c6f-acd6-fccdfb6ff331    3
8c6c5a10-279a-4cee-a40f-a4689489728a    3
9d7dd3c5-9ca6-4248-9c5d-4360118aa0ce    3
f5962450-ac58-4eaa-88a4-804851e5344f    3
7828b977-5ddf-4f5f-87f1-54a63003813d    3
Name: count, dtype: int64

-------------------------------------------------------------------------------------------------------

#### Contunisation of the actual investigation 

In [1150]:
# Normalized first name. example: 'shiv' and 'Shiv' should be treated as same. So, we will normalize the first name by stripping and converting to lower case.
normalized_first_name = (
    non_exact_duplicated_cr_records['first_name']
    .str.strip()
    .str.lower()
)

normalized_first_name


20            kendra
53            denise
62             bruce
118         nicholas
142        christine
            ...     
49920          isaac
49929    jjeennnifer
49947          frank
49959         karina
49974        michael
Name: first_name, Length: 1521, dtype: str

In [1151]:
first_name_analysis = non_exact_duplicated_cr_records[
    ["customer_id", "first_name"]
].copy()

first_name_analysis['normalized_first_name'] = (
    first_name_analysis['first_name']
    .str.strip()
    .str.lower()
)
first_name_analysis.sample(5)

,customer_id,first_name,normalized_first_name
13974,fb7f2296-efb7-40b5-8870-da7d4abc1a26,Kathy,kathy
47393,0930c2c9-7e8d-4d17-83ec-509b5f05802d,Jason,jason
6752,17d48fbf-148c-4a09-a266-ea6713360c7a,STEPHEN,stephen
9610,1e971e6c-38e4-4a25-8f90-e5363f011bfb,Mi4chael,mi4chael
24747,8527bd55-41ee-46fd-9725-f6cd7f6b2d87,jENNIFER,jennifer


In [1152]:
normalized_first_name_variation = (
    first_name_analysis
    .groupby('customer_id')['normalized_first_name']
    .nunique()
)

In [1153]:
normalized_first_name_conflicts = (
    normalized_first_name_variation > 1
)

normalized_first_name_conflicts.sum()

np.int64(287)

In [1154]:
normalized_first_name_conflict_pct = (
    normalized_first_name_conflicts.mean() * 100
)

In [1155]:
normalized_first_name_conflict_pct.round(2)

np.float64(37.37)

In [1156]:
remaining_first_name_conflicts = (
    normalized_first_name_variation[
        normalized_first_name_variation > 1
    ]
)
remaining_first_name_conflicts.shape

(287,)

### Observation

Within the population of CRM records associated with repeated `customer_id` values, **95.18% of customer groups** exhibit variation in the raw `first_name` attribute.

After applying basic case and surrounding-whitespace normalization, the variation rate decreases to **37.37%**.

This indicates that a substantial portion of the observed variation is attributable to representation differences such as capitalization or surrounding whitespace. However, **37.37% of customer groups still contain multiple normalized `first_name` values**, requiring further investigation to determine the nature and Data Quality significance of the remaining variation.

In [1157]:
remaining_first_name_conflicts.head()

customer_id
0167fd2f-c24d-4f99-a133-6678590ae380    2
01c49ac0-9207-4a30-b5c2-87f76b5ee503    2
02114cd2-1da6-42fe-b8c6-04e7d9922b53    2
0296267f-4157-4af2-a940-259a366d0b29    2
032f8a68-d58d-4393-9e51-cafd6015023d    2
Name: normalized_first_name, dtype: int64

In [1158]:
remaining_first_name_conflicts.index[5]

'04cab96c-79f4-4ae0-a92e-1230dd8bf286'

In [1159]:
first_name_analysis[
    first_name_analysis["customer_id"] == "0f0c3a09-df34-4058-84b1-67460c6c0f2a"
]

,customer_id,first_name,normalized_first_name
33693,0f0c3a09-df34-4058-84b1-67460c6c0f2a,Pa7tricia,pa7tricia
42082,0f0c3a09-df34-4058-84b1-67460c6c0f2a,Patricia,patricia


In [1160]:
first_name_analysis[
    first_name_analysis["customer_id"] == "04cab96c-79f4-4ae0-a92e-1230dd8bf286"
]

,customer_id,first_name,normalized_first_name
24508,04cab96c-79f4-4ae0-a92e-1230dd8bf286,DDiiaane,ddiiaane
46422,04cab96c-79f4-4ae0-a92e-1230dd8bf286,Diane,diane


### Observation

Sample-level inspection identified character-level differences in `first_name` values, including extra characters and misspellings. Further population-level analysis is required to determine how widespread these variations are across the remaining **37.37%** of customer groups.

In [1161]:
first_name_analysis.groupby("customer_id")['normalized_first_name'].agg(list)

customer_id
00682ed4-54ac-434e-b800-a4dfa3775f10     [melissa, melissa]
0070c246-7754-46db-a55f-b14188840068       [joseph, joseph]
00c929d1-753c-49a8-af28-eb3ffe0ad087           [tina, tina]
0167fd2f-c24d-4f99-a133-6678590ae380    [michael, mic2hael]
01695a54-eb34-4506-873d-669cc875b8d0           [sean, sean]
                                               ...         
fe7739e0-f3c7-4daa-827d-cfa43275e8bf         [aaron, aaron]
fe824bff-2096-4e9d-b137-84d613947920           [erin, erin]
fe9854ba-9e4f-4382-b996-23d3ac6054b9    [ddaarrren, darren]
febdca03-4f3d-4568-8639-021f315a3920          [john, joh9n]
ff40bbb8-8845-4525-b538-a5992fc0ac28     [stephen, stephen]
Name: normalized_first_name, Length: 768, dtype: object

In [1162]:
first_name_values = (
    first_name_analysis
    .groupby("customer_id")["normalized_first_name"]
    .agg(lambda x: x.unique())
)

remaining_values = first_name_values.loc[
    remaining_first_name_conflicts.index
]

In [1163]:
remaining_values.sample(10)

customer_id
53890019-4803-4621-ade9-05cec16a3946    [wwiillliam, william]
8bbfb51a-209e-4810-910b-83697b94ace0      [pamela, ppaammela]
d1b686b4-188e-49fe-b162-5564a99ef64a          [james*, james]
c6cea585-8a29-4917-9416-6ed1d1ef08da          [bryan, bry5an]
b531fff2-6bf1-4c0c-a289-001d5e54ee36      [rebekah@, rebekah]
1e971e6c-38e4-4a25-8f90-e5363f011bfb      [mi4chael, michael]
1cecb6a2-9e15-4282-aa69-b48a498f386a        [samuel, samu9el]
debae2ce-0f40-43a9-9eb0-0ed77f55c4d1        [jjoorrge, jorge]
bc492f88-b87e-4ce4-b2e3-b0140b14de87        [samu1el, samuel]
8f5b91c8-6f33-4c85-af98-b2cdf68b5e91        [manuel, manuel!]
Name: normalized_first_name, dtype: object

### Observation

The `first_name` attribute contains character-level variations within repeated `customer_id` groups that persist after basic case and whitespace normalization. Observed patterns include numeric and special-character insertion and repeated-character anomalies.

### Objective — Levenshtein Distance Analysis

Measure the character-level similarity between normalized `first_name` values within repeated `customer_id` groups using **Levenshtein distance**.

The objective is to quantify how many character-level edits are required to transform one name representation into another and classify the observed differences as insertion, deletion, or substitution.

This analysis will help determine the nature and severity of the remaining `first_name` variations after basic case and whitespace normalization.

## Investigation — Levenshtein Distance

### Business Question

How similar are the remaining conflicting `first_name` values after basic case and whitespace normalization?

The previous analysis identified character-level variations that persist after normalization, including numeric insertion, repeated characters, and special-character variation.

Levenshtein distance will be used to quantify the minimum number of single-character edits required to transform one normalized name into another.

In [1164]:
%pip install rapidfuzz

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1165]:
from rapidfuzz.distance import Levenshtein

#### Just Testing it Individually 

In [1166]:
Levenshtein.distance("patricia", "patricia")

0

In [1167]:
Levenshtein.distance("patricia", "pa7ricia")

1

In [1168]:
Levenshtein.distance("patricia", "patriciaa")

1

In [1169]:
Levenshtein.distance("patricia", "patrcia")

1

In [1170]:
Levenshtein.distance("patricia", "michael")

7

In [1171]:
Levenshtein.distance("ddiiane", "diane")

2

In [1172]:
values = remaining_values.loc[
    "9cf540a2-7f51-46c6-b37c-02f561978be4"
]

In [1173]:
# Trying to write a code for calculating the levenshtein distance 

# storage container for the results
results = []

# Defining the reference value.
reference = "michael"

# outer iteration for each customer_id
for id, name in remaining_values.items():
    listofvalues = name

    # Defining the reference value.
    reference = name[-1] # Assuming the last value in the list is the reference for comparison

    # innver iteration for each values from a list of values for a customer_id
    for sample in name:
        dist = Levenshtein.distance(reference, sample)

        # store the result 
        result = {
            "reference": reference,
            "varient": sample,
            "levenshtein_distance": dist
        }

        results.append(result)

    



In [1174]:
levenshtein_results = pd.DataFrame(results)

In [1175]:
levenshtein_results.head()

,reference,varient,levenshtein_distance
0,mic2hael,michael,1
1,mic2hael,mic2hael,0
2,aannttonio,antonio,3
3,aannttonio,aannttonio,0
4,ale0x,alex,1


### Observation

Levenshtein distance was applied to normalized `first_name` values within repeated `customer_id` groups to quantify character-level differences between name representations.

The results show examples of:

- **Distance 0** — identical normalized values.
- **Distance 1** — a single character-level difference, such as `mic2hael` vs `michael` or `ale0x` vs `alex`.
- **Distance 3** — multiple character-level differences, such as `aantttonio` vs `antonio`.

This demonstrates that some first-name variations persist after basic case and whitespace normalization and involve character-level differences.

However, Levenshtein distance measures the degree of textual difference; it does not establish which value is correct or confirm that a Data Quality defect exists. Further classification would require business rules, source-system context, or an authoritative customer reference.

For this profiling exercise, the analysis is considered sufficient to demonstrate the nature of the observed variation. Further investigation can be performed if these name discrepancies are determined to have material business impact.

## Customer ID — Duplicate Investigation

### Observation

The CRM dataset contains **50,000 records** and **48,200 distinct `customer_id` values**, resulting in a distinctness rate of **96.4%**.

Further profiling identified:

- **1,734** customer IDs occurring more than once
- **3,534** records associated with repeated customer IDs
- **2,013** records belonging to exact-duplicate groups
- **1,521** non-exact records across **768** customer IDs

### Attribute-Level Investigation

Within the non-exact population, `first_name` and `last_name` showed the primary attribute-level variation.

For `first_name`:

- Raw variation occurred in **95.18%** of affected customer groups.
- After case and whitespace normalization, variation decreased to **37.37%**.
- Remaining differences included character-level variations such as substitutions, insertions, deletions, and repeated characters.
- Levenshtein distance was used to quantify these character-level differences.

### DQ Interpretation

The investigation identified **strong evidence of exact duplicate records** and **potential attribute-level data inconsistencies**.

However, repeated `customer_id` values do not automatically represent a Data Quality defect. Name differences may result from legitimate updates, formatting differences, source-system behavior, or data-entry errors.

Therefore, the profiling establishes **observations and potential DQ issues**, but business rules and authoritative source information are required to confirm the defect and determine the correct customer value.

### Potential Business Impact

Repeated or conflicting customer records may affect customer counts, Customer 360 matching, reporting, segmentation, and the creation of trusted customer profiles.

## Email Attribute Profiling — Objective

The objective of email profiling is to assess the quality of the `email` attribute across key Data Quality dimensions and identify patterns that may require further investigation.

The analysis will examine:

- **Completeness** — identify NULL, empty, whitespace, and placeholder email values.
- **Uniqueness** — assess distinctness and identify repeated email values.
- **Validity** — determine whether email values follow an acceptable email structure.
- **Pattern Consistency** — identify common and unusual email formats or patterns.
- **Potential Duplicate/Shared Values** — investigate whether the same email is associated with multiple `customer_id` values.

The objective is to distinguish **profiling observations from confirmed Data Quality issues** and determine which findings require further business-rule or source-system investigation.

In [1176]:
# Email Investigation 1 - Completeness
crm['email'].isna().sum() # out of 50,000 records, 1,040 records are missing email address.

np.int64(1040)

In [1177]:
crm['email'].isna().mean() * 100 # out of 50,000 records, 2.08% records are missing email address.

np.float64(2.08)

#### Observation: 
The CRM dataset contains 50,000 records, of which 1,040 have a NULL **email** value, representing 2.08% of the dataset.
DQ interpretation: This is a measured completeness observation. It cannot yet be classified as a completeness defect because the mandatory/optional nature of email, including any customer-segment-specific requirements, has not been established.

In [1178]:
# Email Investigation 2 - Uniqueness

email_not_null = crm.loc[crm['email'].notna(), 'email']



In [1179]:
email_not_null.nunique() #48960 - 46363 = 2597. There are 2,597 email-record occurrences beyond the first occurrence of each distinct email value.

46363

In [1180]:
email_counts = email_not_null.value_counts()

In [1181]:
repeated_email = email_counts[email_counts > 1]

In [1182]:
len(repeated_email) # this basically tells, How many distinct values occured more then a once.

2102

In [1183]:
repeated_email.sum() # this basically tells, this many are the emails occured more then a once.

np.int64(4699)

In [1184]:
round((repeated_email.sum() / len(email_not_null)) * 100,2)

np.float64(9.6)

### Observation

Among the **48,960 non-NULL email records**, **4,699 records** belong to email values that occur more than once.

This represents **9.60%** of the non-NULL email population.

The result indicates that repeated email values exist within the CRM dataset and should be investigated further to determine whether they are associated with the same `customer_id` or shared across multiple customers.

At this stage, repeated email values are considered a **profiling observation**, not automatically a Data Quality defect.

In [1185]:
email_not_null.str.contains("@", regex=False).sum()

np.int64(48960)

In [1186]:
email_not_null.str.contains("@", regex=False).mean() * 100

np.float64(100.0)

In [1187]:
# need to check how many "@" are there

count_it = email_not_null.str.count('@')

count_it.value_counts()

email
1    48960
Name: count, dtype: int64

### Observation

The profiling shows that all **48,960 non-NULL email values** contain exactly one `@` character.

- **48,960 (100%)** contain an `@` character.
- **48,960 (100%)** contain exactly one `@` character.
- **0 (0%)** contain multiple `@` characters.
- **0 (0%)** are missing the `@` character within the non-NULL population.

This indicates that the populated email values are structurally consistent with respect to the `@` delimiter.

However, the presence of exactly one `@` character does **not** confirm that the email addresses are valid. Further pattern and format validation is required to assess conditions such as the local part, domain, and top-level domain.

In [1188]:
# Another pattern profiling is required, email can be split into 2 differnet path "local_part @ domain".

email_domain = email_not_null.str.split("@", regex= False).str[1]

email_domain.sample(10)

26083      yahoo.com
37177    hotmail.com
25784      yahoo.com
31744    hotmail.com
46275    hotmail.com
26107      yahoo.com
29921    hotmail.com
39659    hotmail.com
18874      yahoo.com
45261      yahoo.com
Name: email, dtype: object

In [1189]:
# How many domain contain "."

domain_has_dotes = email_domain.str.contains(".", regex= False)

domain_has_dotes.value_counts()



email
True    48960
Name: count, dtype: int64

In [1190]:
# % of how many domain has dotes

domain_has_dotes.mean() * 100

np.float64(100.0)

In [1191]:
# final investication. Need to check both the part "Local" and "domain" are populating

email_local_part = email_not_null.str.split("@", regex= False).str[0]

email_local_part.isna().value_counts()

email
False    48960
Name: count, dtype: int64

In [1192]:
email_domain.str.strip().eq('').value_counts()  # check where there any empty values present in domain side

email
False    48960
Name: count, dtype: int64

In [1193]:
email_local_part.str.strip().eq('').value_counts()  # check where there any empty values present in local part

email
False    48960
Name: count, dtype: int64

## Email Attribute — Profiling Observations

### Completeness

The CRM dataset contains **50,000 records**, of which **48,960 email values are non-NULL** and **1,040 are NULL**, resulting in a NULL rate of **2.08%**.

The NULL values represent a completeness observation. Whether they constitute a Data Quality defect depends on the business requirement for email availability.

### Distinctness and Repeated Values

Among the **48,960 non-NULL email records**, there are **46,363 distinct email values**.

Further analysis identified **4,699 records (9.60%)** belonging to email values that occur more than once.

This indicates that repeated email values exist within the CRM population and requires further investigation to determine whether the repeated emails belong to the same customer or are shared across multiple `customer_id` values.

### Email Pattern Validation

All **48,960 non-NULL email values (100%)** contain exactly one `@` character.

No populated email values were identified with:

- Zero `@` characters
- Multiple `@` characters

This indicates structural consistency with respect to the `@` delimiter.

However, the presence of exactly one `@` character does not by itself establish email validity. Further pattern validation is required to assess the structure of the local part, domain, and other email-format characteristics.

### DQ Interpretation

The email profiling has identified:

- A **2.08% NULL population**
- **9.60% of non-NULL email records associated with repeated email values**
- Consistent presence of exactly one `@` delimiter across the populated email population

These findings are profiling observations. Further business-rule and relationship analysis is required before classifying them as confirmed Data Quality defects.

## Phone Number Attribute Profiling — Objective

The objective of phone number profiling is to assess the quality and structural consistency of the `phone_number` attribute across the CRM population.

The analysis will examine:

- **Completeness** — identify NULL, empty, whitespace, and placeholder phone values.
- **Uniqueness** — assess distinct phone values and identify repeated phone numbers.
- **Pattern and Format** — examine digits, length, special characters, prefixes, and formatting patterns.
- **Validity** — identify phone values that do not conform to the expected structural rules.
- **Customer Association** — investigate whether the same phone number is associated with multiple `customer_id` values.

The objective is to distinguish legitimate formatting and shared-value patterns from potential Data Quality issues and establish evidence for further business-rule investigation.

In [1194]:
# completeness check 
crm['phone_number'].isna().value_counts()

phone_number
False    50000
Name: count, dtype: int64

In [1195]:
crm['phone_number'].isna().mean() * 100

np.float64(0.0)

Completeness observation: All 50,000 CRM records contain a non-NULL phone_number value. The observed NULL rate is 0%, corresponding to 100% non-NULL completeness.

In [1196]:
crm['phone_number'].str.strip().eq('').value_counts()

phone_number
False    50000
Name: count, dtype: int64

Phone-number completeness observation: All 50,000 CRM records contain a non-NULL, non-empty, non-whitespace phone_number value. The observed missing/empty rate is 0%, corresponding to 100% population completeness under the checks performed.

In [1197]:
# moving to patter profiling: Character Composition - Let's first understand what characters are present.

crm['phone_number'].sample(10)

31695             944.327.8125
2993       +1-928-287-1427x639
3449        (842)536-7501x0470
46350          +1-694-964-0750
24236             120.946.6516
37833         001-821-416-5344
49949       (589)947-6714x8060
27327             332.230.6063
8487     001-404-256-6913x8157
12698       505-382-3463x27279
Name: phone_number, dtype: str

In [1198]:
phone_length = crm["phone_number"].str.len()

phone_length.describe()

count    50000.000000
mean        16.149800
std          3.501755
min         10.000000
25%         13.000000
50%         17.000000
75%         19.000000
max         22.000000
Name: phone_number, dtype: float64

The phone_number attribute contains 50,000 populated values with string lengths ranging from 10 to 22 characters. The median length is 17 characters, while the mean is approximately 16.15 characters, indicating that phone-number representations vary substantially in length.

Business question

What characters and formatting patterns are actually present in the phone_number population?

In [1199]:
phone_digit_count = crm['phone_number'].str.count(r"\d")  # any digit from 0 through 9

phone_digit_count.describe()

count    50000.000000
mean        13.035800
std          2.492999
min         10.000000
25%         10.000000
50%         13.000000
75%         15.000000
max         18.000000
Name: phone_number, dtype: float64

The 50,000 phone_number values contain between 10 and 18 numeric digits. The median number of digits is 13, while the mean is approximately 13.04. Therefore, the phone-number population contains multiple digit-length patterns rather than a single fixed digit length.

In [1200]:
# Character / Format Analysis

phone_non_digits = crm['phone_number'].str.replace(r"\d", "",regex= True)

phone_non_digits.value_counts().head(20)

phone_number
..x      6094
()-x     5995
--x      5966
+---x    5964
---x     5947
         4060
--       4023
..       4023
()-      3913
+---     2056
---      1959
Name: count, dtype: int64

In [1201]:
len(phone_non_digits.value_counts())

11

In [1202]:
# Need to take anyone patter and look into the actual value.

pattern = "()-x"

crm.loc[
    phone_non_digits == pattern,
    "phone_number"
].sample(10)

17590     (540)260-3164x1970
23145    (915)834-6726x53450
33156      (126)061-9853x680
9514      (691)186-5062x3958
1167      (976)323-5401x1120
29988     (538)944-5452x7876
43826    (777)467-7366x11364
34978    (775)394-4769x64091
14178     (561)282-9597x3907
40567    (968)668-9135x71210
Name: phone_number, dtype: str

In [1203]:
# Next Investigation - Pattern Vs Dight Count

phone_pattern_analysis = pd.DataFrame({
    'non_digit_pattern': phone_non_digits,
    'digit_count': phone_digit_count
})

In [1204]:
phone_pattern_analysis.head(12).sort_values(by ='digit_count', ascending= False)

,non_digit_pattern,digit_count
6,---x,17
2,+---x,16
1,..x,15
11,..x,14
0,..x,13
9,+---,11
3,--,10
4,..,10
7,..,10
5,()-,10


In [1205]:
phone_pattern_analysis.groupby(
    "non_digit_pattern"
)["digit_count"].value_counts()

non_digit_pattern  digit_count
                   10             4060
()-                10             3913
()-x               13             2052
                   15             2005
                   14             1938
+---               11             2056
+---x              16             2023
                   15             2019
                   14             1922
--                 10             4023
---                13             1959
---x               18             2029
                   17             2016
                   16             1902
--x                14             2015
                   15             1989
                   13             1962
..                 10             4023
..x                13             2074
                   15             2054
                   14             1966
Name: count, dtype: int64

The same formatting pattern does not necessarily correspond to exactly one fixed phone-number length.

The phone-number field contains multiple recurring formatting templates, some of which include extension indicators (x). Digit-count variation within the same pattern appears to be associated with these different numeric components, but this relationship should be verified before classifying the variation as valid or erroneous.

In [1206]:
phone_with_extension = crm[
    crm['phone_number'].str.contains('x', regex= False)
]['phone_number']

phone_with_extension.head(10)

0          449.977.1729x282
1        501.347.4824x64633
2     +1-268-822-6332x26814
6     001-063-045-0948x4636
11        205.022.2886x1126
14      (589)341-8236x24713
15     +1-712-046-0252x3070
17         290-041-9470x081
18         827-308-2086x206
20    +1-362-979-6775x98610
Name: phone_number, dtype: str

The portion before x generally represents the main telephone number, with some records containing an additional country/international dialing prefix. Consequently, the digit count of the main telephone component varies depending on whether such a prefix is present.

In [1207]:
# invistagating the before and after party of the extension

extension_part = phone_with_extension.str.split('x', regex= False)

main_phone = extension_part.str[0]
extension = extension_part.str[1]

In [1208]:
main_phone.head()

0         449.977.1729
1         501.347.4824
2      +1-268-822-6332
6     001-063-045-0948
11        205.022.2886
Name: phone_number, dtype: object

In [1209]:
extension.head()

0       282
1     64633
2     26814
6      4636
11     1126
Name: phone_number, dtype: object

In [1210]:
main_phone_digits = main_phone.str.count(r'\d')
extension_digits = extension.str.count(r'\d')

In [1211]:
main_phone_digits.value_counts().sort_index()

phone_number
10    18055
11     5964
13     5947
Name: count, dtype: int64

In [1212]:
extension_digits.value_counts().sort_index()

phone_number
3     9912
4     9954
5    10100
Name: count, dtype: int64

In [1213]:
phone_has_extension = crm["phone_number"].str.contains("x", regex=False)

phone_has_extension.value_counts()

phone_number
True     29966
False    20034
Name: count, dtype: int64

In [1214]:
round(phone_has_extension.mean() * 100, 2)

np.float64(59.93)

### Objective

Assess the distinctness and repetition of `phone_number` values to determine how many distinct phone numbers exist and how many CRM records share the same phone number.

In [1215]:
crm['phone_number'].nunique()

46777

In [1216]:
crm['phone_number'].nunique() / len(crm) * 100

93.554

In [1217]:
phone_counts = crm['phone_number'].value_counts()

repeated_phone = phone_counts[phone_counts > 1]

In [1218]:
repeated_phone[repeated_phone == 9].head(10)

phone_number
586-049-5136             9
154.878.2024             9
001-836-144-1830         9
+1-909-524-5319x40721    9
+1-612-587-5981x73649    9
434.256.8275x442         9
001-275-793-6721         9
909.483.2481x6822        9
+1-510-098-1404x9349     9
249-826-8747             9
Name: count, dtype: int64

Are repeated phone numbers associated with the same customer or with multiple customer IDs?

In [1219]:
repeated_phone_records = crm[
    crm['phone_number'].isin(repeated_phone.index)
]

In [1220]:
repeated_phone_records.shape

(5384, 14)

In [1221]:
repeated_phone_records['phone_number'].nunique()  # accross 5384 records, around 2161 phone number are distinct.

2161

For each repeated phone number, how many distinct customer IDs are associated with it?

In [1222]:
phone_customer_analysis = (
    repeated_phone_records
    .groupby("phone_number")["customer_id"]
    .nunique()
)

In [1223]:
phone_customer_analysis

phone_number
(001)088-8066x63421    1
(001)547-4316x0431     1
(010)388-7379x913      1
(014)453-0953x87025    1
(014)990-2831x9412     7
                      ..
995.167.0819x8497      1
995.662.7963x98393     1
997-706-6171x16093     2
998.004.4424           3
999-696-5029x95945     1
Name: customer_id, Length: 2161, dtype: int64

In [1224]:
phone_customer_analysis.value_counts().sort_index()

customer_id
1    1661
2     114
3     127
4     109
5      69
6      50
7      19
8       8
9       4
Name: count, dtype: int64

How many CRM records are affected by those 500 cross-customer phone values?

In [1225]:
cross_customer_phones = phone_customer_analysis[
    phone_customer_analysis > 1
]

In [1226]:
cross_customer_records = repeated_phone_records[
    repeated_phone_records["phone_number"].isin(cross_customer_phones.index)
]

In [1227]:
cross_customer_records.shape

(2002, 14)

In [1228]:
cross_customer_records["phone_number"].nunique()

500

In [1229]:
round(
    len(cross_customer_records) / len(crm) * 100,
    2
)

4.0

Let's determine how many customers are associated with each shared phone number.

In [1230]:
cross_customer_phones

phone_number
(014)990-2831x9412    7
(023)543-5157         5
(040)632-8321         2
(041)462-1023x702     3
(047)837-3553x0327    6
                     ..
983.824.0314x71939    4
985.565.5722          5
9923107436            6
997-706-6171x16093    2
998.004.4424          3
Name: customer_id, Length: 500, dtype: int64

In [1231]:
cross_customer_phones.value_counts().sort_index()

customer_id
2    114
3    127
4    109
5     69
6     50
7     19
8      8
9      4
Name: count, dtype: int64

## Phone Number Profiling — Observation

### Observation

The `phone_number` attribute was profiled across completeness, uniqueness, digit structure, formatting patterns, and customer association.

The profiling identified the following:

- The attribute is fully populated based on the NULL, empty, and whitespace checks performed.
- Phone numbers contain different digit counts and formatting patterns, indicating multiple representations within the CRM dataset.
- Non-digit analysis identified formatting characters such as spaces, hyphens, parentheses, and other characters.
- Repeated phone numbers were identified within the CRM population.
- Customer-association analysis showed that some phone numbers are associated with multiple distinct `customer_id` values. The observed distribution ranges from **1 to 9 distinct customers per phone number**.
- **1,661 phone numbers** are associated with exactly one distinct `customer_id`, while the remaining repeated phone numbers are associated with multiple customer IDs.

### DQ Interpretation

The profiling identified **phone-number format variation and shared phone numbers** as potential Data Quality risks.

However, a phone number being associated with multiple customers does not automatically represent a Data Quality defect, as shared household or business contact numbers may be legitimate.

Further classification would require an approved business rule and additional source-system or customer context.

### Objective

Assess the `dob` attribute for completeness, date validity, temporal anomalies, and consistency with related date attributes such as `signup_date`, while identifying potential Data Quality risks requiring further investigation.

In [1232]:
# first investication: does dob attribute structurally and temporally valid?

crm['dob'].isna().sum()

np.int64(0)

In [1233]:
crm['dob'].nunique()

17733

The dob attribute is populated for all 50,000 CRM records, resulting in 100% NULL-level completeness. The attribute contains 17,733 distinct DOB values.

In [1234]:
# trying to covert the dob(text to data&time). this is called the prasing. error = coerce: mean returing if the values is not a time, then retunrs "NaT". 

dob_parsed = pd.to_datetime(
    crm['dob'],
    errors="coerce"
)



In [1235]:
dob_parsed[dob_parsed.isna()]

Series([], Name: dob, dtype: datetime64[us])

All 50,000 populated dob values were successfully parsed as dates using the applied pandas datetime parsing operation. No parsing failures were observed.

In [1236]:
# trying to understand, temporal validation. means data makes logical sence in a real world seniro.
# finding, is there any dates > then todays data?

today = pd.Timestamp.today().normalize()
future_dob = dob_parsed > today
future_dob.sum()

np.int64(0)

In [1237]:
round(future_dob.mean() * 100, 2)

np.float64(0.0)

In [1238]:
# Business Question: What ages do the DOB values imply?
# calculating the age of the customer.

age_years = (
(today - dob_parsed).dt.days / 365.25
)

age_years.describe()

count    50000.000000
mean        45.368269
std         15.233085
min         18.836413
25%         32.166324
50%         45.355236
75%         58.507871
max         71.800137
Name: dob, dtype: float64

In [1239]:
# analysing, is any customer signed up before he borned.

# data_praising for sign_up_date

signup_prased = pd.to_datetime(
    crm['signup_date'],
    errors='coerce'
)

signup_prased.isna().sum()

np.int64(0)

In [1240]:
# cross-column profiling 

dob_after_signup  = dob_parsed >= signup_prased

dob_after_signup.sum()


np.int64(0)

## DOB Profiling — Observation

### Observation

The `dob` attribute contains **50,000 populated values** with **0 NULL values**, resulting in **100% NULL-based completeness**.

The profiling identified:

- **17,733 distinct DOB values**
- **0 datetime parsing failures**
- **0 future DOB values**
- An implied age range of approximately **18.8 to 71.8 years**
- **0 records** where `dob >= signup_date`

These results indicate that the DOB values are structurally parseable and do not exhibit the tested temporal anomalies or inconsistencies with `signup_date`.

### DQ Interpretation

No significant Data Quality issue was identified for `dob` based on the profiling rules applied.

Further investigation is not required at this stage unless additional business requirements introduce more specific DOB validation rules.


## Gender Attribute Profiling — Objective

Assess the `gender` attribute for completeness, distinct values, categorical validity, and representation consistency to identify unexpected, missing, placeholder, or non-standard category values that may represent potential Data Quality risks.

In [1241]:
# identifying the completeness 
crm['gender'].isna().sum()

np.int64(0)

In [1242]:
#identifying how many distinct values are there
crm['gender'].nunique()

3

In [1243]:
crm['gender'].value_counts(dropna=False)

gender
F    23333
M    22880
O     3787
Name: count, dtype: int64

The observed gender domain contains three populated categories: F, M, and O. No NULL values were observed.

In [1244]:
# investigating the categorical representation profiling.

crm['gender'].unique()

<StringArray>
['M', 'F', 'O']
Length: 3, dtype: str

In [1245]:
crm['gender'].str.strip().ne(crm['gender']).sum()

np.int64(0)

## Gender Profiling — Observation

### Observation

The `gender` attribute contains **50,000 records** with **0 NULL values**, resulting in **100% NULL-based completeness**.

The profiling identified **3 distinct categories**:

- `F` — 23,333 records
- `M` — 22,880 records
- `O` — 3,787 records

No leading or trailing whitespace variations were identified, and no case-format variation was observed.

### DQ Interpretation

The `gender` values are structurally consistent within the observed categories. However, whether `F`, `M`, and `O` represent the complete and approved business domain cannot be determined from profiling alone.

Confirmation of the allowed gender domain should be obtained from the relevant business or data owner before classifying any category as invalid.

### Objective

Assess the `device_id(s)` attribute to determine whether it represents single or multiple device identifiers within a field, and profile its completeness, physical representation, distinctness, and device-to-customer relationships to identify potential Customer 360 Data Quality risks.

In [1246]:
crm['device_id(s)'].head(5)

0    56f3a452-b3f5-488b-b90d-8cb2b3343c70;3ab7d21b-...
1                 cd83e240-0d50-4e67-b146-23deb6c49940
2                 369b8950-dfae-44ce-bbb4-d292f118be67
3                 3e83071f-53ed-4a05-9dfd-5ff2031443b5
4                 751d4410-3d73-4f4c-b432-10a0213b925f
Name: device_id(s), dtype: str

In [1247]:
crm['device_id(s)'].nunique()

48200

In [1248]:
crm['device_id(s)'].isna().sum()

np.int64(0)

The device_id(s) attribute contains no NULL values and 48,200 distinct raw string values across 50,000 CRM records.

In [1249]:
# need to identfiy, how many records have multiple device id's

device_has_multiple = crm['device_id(s)'].str.contains(';', regex= False)

device_has_multiple.sum()

np.int64(1252)

In [1250]:
round(device_has_multiple.mean() * 100, 2)

np.float64(2.5)

In [1251]:
device_count = crm['device_id(s)'].str.split(";", regex= False).str.len()

In [1252]:
device_count.value_counts()

device_id(s)
1    48748
5      263
6      256
2      248
4      246
3      239
Name: count, dtype: int64

97.50% of CRM records contain a single device ID, while 2.50% contain multiple device IDs, with observed cardinality ranging from 2 to 6 devices per record.


A customer legitimately having six devices is entirely possible. What we've discovered is that device_id(s) is a multi-valued attribute, even though it is physically stored in a single column.

In [1253]:
device_ids = crm['device_id(s)'].str.split(";", regex= False).explode().str.strip()

device_ids.nunique()

51854

In [1254]:
device_ids.isna().sum()

np.int64(0)

In [1255]:
device_ids.str.strip().eq("").sum()

np.int64(0)

It means that, based on this analysis, every logical device ID occurs only once across the expanded CRM population.

In other words:
No device ID was observed more than once across the 51,854 logical device occurrences.


In [1256]:
# What is the maximum number of CRM occurrences associated with any single logical device ID?

device_counts = device_ids.value_counts()

device_counts.max()

np.int64(4)

My previous interpretation that every logical device ID occurred once was incorrect. Your device_counts.max() result of 4 tells us that at least one logical device ID appears up to four times in the expanded data.

In [1257]:
# Are repeated device IDs repeated for the same customer, or are they shared across different customers?

repeated_devices = device_counts[device_counts > 1]

repeated_devices.sort_index(ascending= False).head()

device_id(s)
ffe3d8f6-34c8-4c36-9837-56b1c7c73dfb    2
ffab6556-0884-4c9f-abd3-2dd037f9fc99    2
ff5f10e7-54c7-4c20-b656-ccaea82b48b2    2
ff4404c7-c057-48a1-a5f7-d1b5f495f3ec    2
ff403cb4-64c2-45f0-b08a-7ff2fdf698fa    2
Name: count, dtype: int64

In [1258]:
device_customer = (
    crm[["customer_id", "device_id(s)"]]
    .assign(device_id=crm["device_id(s)"].str.split(";", regex=False))
    .explode("device_id")
)

device_customer["device_id"] = device_customer["device_id"].str.strip()

In [1259]:
device_customer.groupby("device_id")["customer_id"].nunique().sort_values(ascending=False).head(20)

device_id
000068d4-f22b-48e7-af15-13d582d2cbfd    1
0000e6cb-c5e2-486f-a652-4c9ac5906865    1
000458dd-a4c8-4e7a-873b-bdb56ce16215    1
00054161-f39c-4525-90c2-f5ae1c90182c    1
0007656f-28c2-4a83-9464-53a8d1556139    1
0008b8e2-5211-45fb-8ccc-54defff14845    1
00099dfd-67d8-4019-b90e-af40e6bd5d47    1
000a2454-11bd-43d2-a4fd-44d66a5d0ab3    1
000aa534-132f-4b73-9a79-7184fc390367    1
000bfcb9-75c7-4b24-9bd1-9f8349932865    1
000d6b28-4b8d-453c-b7ea-8b4b7c2d208a    1
000e0e0c-3e2f-4a81-8756-2f0717554e2c    1
000e8552-fe0d-4fa0-abf7-fa40bc261ddc    1
0013ceb5-1f12-4a68-9778-b8334d58e979    1
00143c95-1040-4903-8994-e5c69fec91ea    1
0014c844-45a4-41c7-acb6-7ad9d9a9f97a    1
0019d376-721d-44cf-8e72-dad0879fe799    1
001ac03f-1439-4afe-9daa-f29f658567e0    1
001eb296-1e2c-4237-937f-817fb65e4c49    1
00200c5a-c6af-4e6f-bf59-33c69de6bb21    1
Name: customer_id, dtype: int64

In [1260]:
device_customer_counts = (
    device_customer
    .groupby("device_id")["customer_id"]
    .nunique()
)

cross_customer_devices = device_customer_counts[
    device_customer_counts > 1
]

cross_customer_devices.sort_values(ascending=False)

Series([], Name: customer_id, dtype: int64)

In [1261]:
len(cross_customer_devices)

0

## Device ID(s) Profiling — Observation

### Observation

The `device_id(s)` attribute contains **no NULL or empty logical device IDs** across the 50,000-record CRM population.

The profiling identified **1,252 records (2.50%)** containing multiple device IDs, resulting in **51,854 logical device-ID occurrences** across the CRM dataset.

Further customer-association analysis found **no device ID associated with multiple distinct `customer_id` values**.

### DQ Interpretation

The `device_id(s)` attribute shows a multi-valued representation in a small portion of the CRM records, but no cross-customer device-sharing anomaly was identified in the profiled population.

The multi-valued structure should be considered an important **data-model/profiling observation**, while no confirmed Data Quality defect was identified based on the rules investigated.

## Cross-Column Profiling — Objective

Assess relationships and consistency between related CRM attributes to identify combinations, dependencies, or contradictions that may not be detectable through individual column profiling, and determine potential Data Quality risks affecting the Customer 360 view.


In [1262]:
# Are repeated email addresses associated with the same customer ID or multiple customer IDs?

email_customer = crm[['email', 'customer_id']].dropna(subset= ['email'])

In [1263]:
email_customer_counts = email_customer.groupby('email')['customer_id'].nunique()

In [1264]:
cross_customer_emails = email_customer_counts[email_customer_counts > 1]

In [1265]:
# How many customer IDs are associated with those emails?

cross_customer_emails.sum()

np.int64(1287)

In [1266]:
# How many email addresses are associated with multiple customers?

len(cross_customer_emails)

450

In [1267]:
# how many customer recoreds are affected 

cross_customer_records = email_customer[
    email_customer['email'].isin(cross_customer_emails.index)
]



In [1268]:
len(cross_customer_records)

1333

In [1269]:
affected_customer_ids  = cross_customer_records['customer_id'].nunique()

affected_customer_ids

1287

In [1270]:
round(affected_customer_ids / len(crm) * 100,2)

2.57

Approximately 450 email addresses are associated with multiple customer IDs, affecting 1,333 CRM records and 1287 distinct customers, representing 2.57% of the CRM population.

In [1271]:
cross_customer_records.sort_values('email').head()

,email,customer_id
29052,bryan.harris874@hotmail.com,854cea92-9b38-427f-8a5f-3c9679b5f04b
26342,bryan.harris874@hotmail.com,3fe325d1-d05c-4e61-b280-c1d7e758e212
3774,gary.long108@gmail.com,745789d6-0aec-42d1-8175-a99eda6bbace
16286,gary.long108@gmail.com,565103a1-2f23-4851-86d7-6bfb94cc00a2
14746,james.miller772@hotmail.com,01ec711f-b4f9-4f97-a16f-66b51dc4130a


Multiple distinct customer_id values are associated with the same email address in the CRM dataset.

In [1272]:
# inspecting one emial address, wether same other attributes are repiting or not.

email_example = 'gary.long108@gmail.com'

crm.loc[
    crm['email'] == email_example,
    ["customer_id", "first_name", "last_name",
     "phone_number", "dob", "signup_date"]
]

,customer_id,first_name,last_name,phone_number,dob,signup_date
3774,745789d6-0aec-42d1-8175-a99eda6bbace,Gary,LLoonng,+1-749-811-2979x402,1957-08-08,2017-01-18
16286,565103a1-2f23-4851-86d7-6bfb94cc00a2,Gary,lONG,(261)417-4513x034,1973-01-04,2015-01-05


## Cross-Column Profiling — Email ↔ Customer ID

### Observation

The cross-column analysis identified email values that are associated with
multiple `customer_id` values within the CRM dataset.

Earlier email profiling identified **4,699 records (9.60% of the non-NULL
email population)** belonging to repeated email values. The cross-column
analysis demonstrated that repeated email values cannot be evaluated through
email uniqueness alone; their relationship with `customer_id` must also be
considered.

Some repeated email values are associated with more than one customer,
indicating a potential Customer 360 identity and data-association risk.

### DQ Interpretation

A shared email address does not automatically represent a Data Quality
defect. Legitimate scenarios such as shared household or business email
addresses may exist.

However, where the business rule expects email to uniquely identify a
customer, an email associated with multiple `customer_id` values would
represent a potential uniqueness/identity-resolution issue requiring further
business validation.

The finding therefore represents a **potential Data Quality risk rather than
a confirmed defect** without an approved business rule defining email
uniqueness.

## Cross-Table Profiling — Objective

Assess the relationships between key attributes across the Customer 360 datasets to determine whether the sources can be reliably integrated. The profiling will focus on table relationships, key overlap, referential integrity, unmatched records, relationship coverage, and cardinality to identify potential cross-system Data Quality risks and their possible impact on Customer 360 integration.

Here we imported the Dataset 

In [1273]:
for file in data_path.iterdir():   #this is help to itrate all the file from a floder
    print(file.name)

clickstream_500k_events.csv
crm_50000_customers_dirty_v3.csv
orders_300k_dirty.csv
product_catalog_dirty_30pct.csv
support_tickets_30000_dirty.csv


In [1274]:
orders = pd.read_csv(r"C:\Users\Shivshankar_RaviMala\python_code\customer_360_data_quality\data\orders_300k_dirty.csv")
Products = pd.read_csv(r"C:\Users\Shivshankar_RaviMala\python_code\customer_360_data_quality\data\product_catalog_dirty_30pct.csv")
support_ticket = pd.read_csv(r"C:\Users\Shivshankar_RaviMala\python_code\customer_360_data_quality\data\support_tickets_30000_dirty.csv")
clickstream = pd.read_csv(r"C:\Users\Shivshankar_RaviMala\python_code\customer_360_data_quality\data\clickstream_500k_events.csv")

In [1275]:
print("CRM:", crm.shape)
print("Orders:", orders.shape)
print("Products:", Products.shape)
print("Support:", support_ticket.shape)
print("Clickstream:", clickstream.shape)

CRM: (50000, 14)
Orders: (300000, 8)
Products: (500, 4)
Support: (30000, 8)
Clickstream: (500000, 8)


In [1276]:
print("\nCRM")
print(crm.columns.tolist())

print("\nOrders")
print(orders.columns.tolist())

print("\nProducts")
print(Products.columns.tolist())

print("\nSupport")
print(support_ticket.columns.tolist())

print("\nClickstream")
print(clickstream.columns.tolist())


CRM
['customer_id', 'first_name', 'last_name', 'email', 'phone_number', 'gender', 'dob', 'signup_date', 'address', 'city', 'state', 'country', 'device_id(s)', 'source']

Orders
['order_id', 'customer_id', 'product_id', 'order_amount', 'order_date', 'payment_method', 'status', 'quantity']

Products
['product_id', 'product_name', 'category', 'price']

Support
['ticket_id', 'customer_id', 'issue_type', 'ticket_created', 'ticket_resolved', 'resolution_time_hours', 'sentiment', 'support_agent']

Clickstream
['event_id', 'session_id', 'customer_id', 'event_type', 'page_url', 'device_id', 'timestamp', 'ingest_run_id']


In [1277]:
# before setting the relationship, need to identify whether support keys are actually a unique.

orders['order_id'].nunique()

300000

In [1278]:
orders["order_id"].isna().sum()

np.int64(0)

In [1279]:
order_counts = orders["order_id"].value_counts()

order_counts[order_counts > 1].head(10)

Series([], Name: count, dtype: int64)

In [1280]:
len(order_counts[order_counts > 1])

0

All 300,000 Orders records have a distinct, non-null order_id; no repeated order IDs were identified. This supports treating order_id as the candidate key for the Orders table.

In [1281]:
#Business Question: Does every customer referenced by an order exist in the CRM customer population?

crm_customer_ids = crm['customer_id'].unique()

In [1282]:
orders['customer_id'].isin(crm_customer_ids).sum()

np.int64(300000)

The Orders table has complete referential coverage against the CRM customer_id population, but the CRM customer_id attribute is not unique. Consequently, the relationship has no orphan-order issue under the tested rule, but customer-level relationship ambiguity may still exist.

In [1283]:
# For customer IDs referenced by Orders, how many CRM records exist for each customer ID?

crm_customer_counts = crm['customer_id'].value_counts()

In [1284]:
repeated_crm_customers = crm_customer_counts[crm_customer_counts > 1]

In [1285]:
len(repeated_crm_customers)

1734

In [1286]:
repeated_crm_customers.sum()

np.int64(3534)

In [1287]:
orders['customer_id'].isin(repeated_crm_customers.index).sum()

np.int64(21073)

21,073 Orders records reference a customer_id that occurs multiple times in the CRM dataset.

In [1288]:
round(21073 / len(orders) * 100, 2)

7.02

1,734 customer IDs are repeated in CRM, representing 3,534 CRM records. Of the 300,000 Orders records, 21,073 (7.02%) reference these repeated customer IDs. While no orphan Orders were identified, these relationships may introduce customer identity ambiguity when Orders are joined to CRM.

In [1289]:
repeated_ids_used_by_orders = orders.loc[
    orders['customer_id'].isin(repeated_crm_customers.index),
    'customer_id'
].nunique()

In [1290]:
repeated_ids_used_by_orders

1734

Referential existence is satisfied: all 300,000 Orders records reference a customer ID present in CRM. However, all 1,734 customer IDs that are repeated within CRM are also referenced by Orders, affecting 21,073 Orders (7.02%). This creates a potential customer-identity ambiguity when Orders are integrated with CRM because the referenced customer ID does not uniquely identify one CRM record.

In [1291]:
# When Orders is actually joined to CRM, do those duplicate CRM IDs cause Orders records to multiply?

orders_crm = orders.merge(
    crm, 
    on='customer_id',
    how = 'left'
)

In [1292]:
len(orders)

300000

In [1293]:
len(orders_crm )

322293

In [1294]:
round(
    (len(orders_crm) - len(orders)) / len(orders) * 100,
    2
)

7.43

## Cross-Table Profiling — CRM ↔ Orders Observation

The CRM `customer_id` is non-unique: **1,734 repeated customer IDs** are referenced by Orders, affecting **21,073 Order records**.

When Orders are joined to CRM on `customer_id`, the result increases from **300,000 to 322,293 rows**, representing **22,293 additional rows (7.43% expansion)**.

This demonstrates that duplicate CRM customer IDs can cause **row multiplication during integration**, creating potential customer identity ambiguity and downstream aggregation/reporting risks in the Customer 360 environment.

## Cross-Table Profiling — CRM ↔ Orders Observation

The cross-table investigation identified a significant relationship-level Data Quality risk between the CRM and Orders datasets:

| Measurement | Result | Meaning |
|---|---:|---|
| Repeated CRM `customer_id` values | **1,734** | Customer IDs appearing multiple times in CRM |
| Orders using those repeated IDs | **21,073** | Distinct Orders referencing duplicated CRM customer IDs |
| Additional rows created by the join | **22,293** | Row expansion caused by multiple CRM matches |

The findings demonstrate that the issue is not limited to duplicate `customer_id` values within CRM. When Orders are joined to CRM using `customer_id`, the non-unique CRM identifiers cause **row multiplication**, increasing the joined population from **300,000 to 322,293 rows**.

This indicates a potential **customer identity ambiguity and downstream integration risk** for Customer 360 processes, particularly where joined data is used for aggregation, reporting, or customer-level analysis.

## Objective — Product ↔ Orders Cross-Table Profiling

Assess the relationship between the **Products** and **Orders** datasets to determine whether product references in Orders are complete, valid, unique, and structurally consistent with the Product master.

The investigation will focus on:

- Identifying whether every `product_id` referenced by Orders exists in Products.
- Measuring unmatched or orphan product references.
- Checking whether `product_id` is unique in the Products dataset.
- Determining whether duplicate Product IDs can cause row multiplication during joins.
- Measuring the downstream impact of any Product ↔ Orders relationship issues.

The objective is to move beyond column-level profiling and determine whether the **Product master can reliably support Orders integration and downstream Customer 360 analytics**.

In [1295]:
# need to identify whether prodcut.product_id act as a referenc key.

Products['product_id'].nunique()

500

In [1296]:
Products['product_id'].isna().sum()

np.int64(0)

product_id is unique and non-null, and therefore satisfies the basic structural requirements of a candidate primary key.

In [1297]:
# Does every product_id appearing in Orders exist in the Products table?

product_ids = Products['product_id'].unique()

orders['product_id'].isin(product_ids).sum()

np.int64(300000)

All 300,000 Orders records reference a product_id present in the Products table. No orphan product references were identified in the observed dataset, indicating referential integrity between Orders and Products for the tested product_id relationship.


In [1298]:
# Are the order quantities and order amounts logically consistent with the product prices?

orders[['order_amount', 'quantity']].describe()

,order_amount,quantity
count,287170,300000
unique,244090,10
top,0,3
freq,12988,45296


In [1299]:
Products['price'].describe()

count       474
unique      402
top       1,200
freq         30
Name: price, dtype: object

Based on the observation: there are missing values found in the order_amount and the products.price. Need futher investication.

In [1300]:
orders['order_amount'].isna().sum()

np.int64(12830)

In [1301]:
Products['price'].isna().sum()

np.int64(26)

In [1302]:
orders["order_amount"].dropna().head(20)

0        473.82
1      17796.32
2      31201.75
3      42282.89
4      27100.3 
5       2393.67
6      12532.69
7      47079.63
8      32901.99
9       3858.55
10     26531.19
11     40344.97
12    41711.08 
13     29184.75
14     8581.57 
15          -50
16     40904.93
17     35036.68
18          -50
19      4016.76
Name: order_amount, dtype: str

In [1303]:
Products["price"].dropna().head(20)

0      32309.95
1      47346.82
2          -100
3      28506.95
4      19165.58
5        2215.4
6       49101.1
7      20599.53
8      27710.51
9             0
10     38495.28
11     35426.08
12     46067.97
13     26010.64
14     29803.79
15        1,200
16      30310.1
17            0
19        1,200
20     40642.04
Name: price, dtype: str

Negative product prices were observed and require business-rule validation. If Products.price represents a standard non-negative selling price, these records would violate the expected validity rule.

In [1304]:
Products['price'].astype(str).str.replace(',', '').astype(float).lt(0).sum()

np.int64(26)

In [1305]:
Products["price"].astype(str).str.replace(",", "").astype(float).eq(0).sum()

np.int64(19)

In [1306]:
orders['order_amount'].astype(str).str.replace(',', '').astype(float).lt(0).sum()

np.int64(12810)

In [1307]:
orders['order_amount'].astype(str).str.replace(',', '').astype(float).eq(0).sum()

np.int64(12988)

12,810 Orders have negative order_amount values (approximately 4.27% of the Orders population). This is an anomaly requiring business-rule validation; negative values are not automatically Data Quality defects because transaction reversals or refunds could legitimately produce negative amounts.

In [1308]:
negative_orders = orders[
    orders['order_amount'].astype(str).str.replace(',',"").astype(float) < 0
]

negative_orders['status'].value_counts(dropna= False)

status
success      7802
refunded      745
Success       574
REF           568
refunded      551
SUCCESS       550
 FAILED       549
fail          521
suc           515
failed        435
Name: count, dtype: int64

In [1309]:
status_mapping = {
    'success': 'success',
    'Success': 'success',
    'SUCCESS': 'success',
    'suc': 'success',

    'refunded': 'refund',
    'REF': 'refund',
    'refunded': 'refund',

    ' FAILED': 'failed',
    'fail': 'failed',
    'failed': 'failed'
}

In [1310]:
negative_orders = negative_orders['status'].map(status_mapping)

In [1311]:
orders["status"].value_counts(dropna=False)

status
success      182599
refunded      16990
SUCCESS       12955
refunded      12936
REF           12901
suc           12874
Success       12852
fail          12760
 FAILED       12722
failed        10411
Name: count, dtype: int64

In [1312]:
negative_orders

15         refund
18        success
24        success
37        success
47        success
           ...   
299817    success
299821    success
299826     refund
299876    success
299909     failed
Name: status, Length: 12810, dtype: str

### ⚠️ Profiling Note — Temporary Transformation

During the investigation, I temporarily applied the `status_mapping` transformation directly to the `negative_orders["status"]` column.

This modified the derived profiling subset, but **did not modify the original `orders` DataFrame**.

The original `orders` dataset was verified using `value_counts()` and confirmed to retain the raw status values.

**Lesson:** Raw data should remain unchanged during profiling. Any transformations should be performed on a separate profiling copy or derived representation.

The `negative_orders` subset was therefore recreated from the original `orders` DataFrame before continuing the analysis.

In [1313]:
negative_orders = orders[
    orders['order_amount'].astype(str).str.replace(',', '').astype(float) < 0
]

In [1314]:
negative_orders['status'].value_counts()

status
success      7802
refunded      745
Success       574
REF           568
refunded      551
SUCCESS       550
 FAILED       549
fail          521
suc           515
failed        435
Name: count, dtype: int64

In [1315]:
negative_orders['status'] = negative_orders['status'].map(status_mapping)

In [1316]:
negative_orders['status'].value_counts()

status
success    9441
failed     1505
refund     1313
Name: count, dtype: int64

In [1317]:
pd.crosstab(
    negative_orders['status'],
    columns='negative_amount_orders'
)

col_0,negative_amount_orders
status,
failed,1505
refund,1313
success,9441


this total is 11,710, whereas your earlier negative-order count was 12,810. So 1,100 negative orders are not represented in this output. We should investigate that discrepancy before making a final conclusion.

In [1318]:
import numpy as np

In [1319]:
orders['amount_sign'] = np.where(
    orders['order_amount'].astype(str).str.replace(',', '').astype(float) < 0,
    'negative',
    'non_negative'
)

In [1320]:
pd.crosstab(
    orders['status'],
    orders['amount_sign']
)

amount_sign,negative,non_negative
status,,
FAILED,549,12173
REF,568,12333
SUCCESS,550,12405
Success,574,12278
fail,521,12239
failed,435,9976
refunded,745,16245
refunded,551,12385
suc,515,12359


### Observation — Order Amount and Status Consistency

The Orders dataset contains negative `order_amount` values across multiple
status representations, including successful, failed, and refund-like
statuses.

Notably, 7,802 records with status `success` have negative order amounts.

This indicates that negative amounts are not exclusively associated with
refund-like statuses in the observed data.

Whether negative amounts under `success` or `failed` represent a Data Quality
defect requires confirmation of the approved business rule for refunds,
reversals, adjustments, and failed transactions.

Additionally, the `status` attribute contains multiple representations such
as `success`, `Success`, `SUCCESS`, and `suc`, indicating a potential
standardization/validity issue requiring confirmation of the approved status
domain.

## Objective — Quantity ↔ Order Amount ↔ Product Price

Assess whether `order_amount` is logically consistent with the **ordered quantity** and the corresponding **Product `price`**.

The investigation will determine whether observed differences indicate expected business behavior or potential Data Quality issues.

In [1321]:
products_price_num = Products['price'].astype(str).str.replace(',','', regex=False).astype(float)

In [1322]:
order_amount_num = orders['order_amount'].astype(str).str.replace(',','', regex=False).astype(float)

In [1323]:
orders_product = orders.merge(
    Products[["product_id", "price"]],
    on="product_id",
    how="left"
)

In [1324]:
orders_product["price_num"] = (
    orders_product["price"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .astype(float)
)

orders_product["order_amount_num"] = (
    orders_product["order_amount"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [1325]:
orders_product['expected_amount'] = (
    orders_product['price_num']
    *
    orders_product['quantity']
        .astype(str)
        .str.replace(',', '', regex=False)
        .astype(float)
)

ValueError: could not convert string to float: ' '

### Observation

The calculation could not be completed because the `quantity` attribute contains non-numeric values. Further investigation identified textual values such as `"Five"`. This indicates that the attribute does not consistently conform to the expected numeric representation.

### Data Quality Implication

The `quantity` attribute requires a validity rule defining the accepted representation of quantity values.

### Important

The original source value has not been modified because this profiling exercise is intended to assess the raw data rather than cleanse it.

In [ ]:
orders['quantity'].value_counts()

quantity
3       45296
2       45234
4       45058
1       44765
5       44647
five    15097
        15050
2.0     15036
-3      14939
0       14878
Name: count, dtype: int64

## Observation — Quantity Representation

The `quantity` attribute contains mixed representations. Most values are numeric, but a textual value such as `five` is also present.

This prevents direct numeric conversion of the full attribute and indicates a **potential validity/standardization issue** in the quantity field.

Further investigation is required to determine the complete set of non-numeric quantity representations and whether values such as `0` and negative quantities are permitted by the business rules.

In [ ]:
orders['quantity'].isna().sum()

np.int64(0)

In [ ]:
orders["quantity"].astype(str).str.strip().value_counts(dropna=False)

quantity
3       45296
2       45234
4       45058
1       44765
5       44647
five    15097
        15050
2.0     15036
-3      14939
0       14878
Name: count, dtype: int64

The quantity column contains no actual NULL values, but approximately 15,050 records contain an empty-string representation after whitespace normalization.

In [ ]:
orders.loc[
    orders["quantity"].astype(str).str.strip().eq(""),
    "quantity"
].value_counts(dropna=False)

quantity
    15050
Name: count, dtype: int64

In [ ]:
orders.loc[
    orders["quantity"].astype(str).str.strip().eq(""),
    "quantity"
].head(10).tolist()


[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']

The quantity attribute contains 15,050 whitespace-only values (5.02% of the 300,000 order records). No actual NULL/NaN values were detected. These values represent missing quantity information and should be treated as a completeness/standardization concern pending the business rule for mandatory quantity.

In [ ]:
quantity_num = pd.to_numeric(
    orders["quantity"].astype(str).str.strip(),
    errors="coerce"
)

In [ ]:
quantity_num

0         1.0
1         1.0
2         2.0
3         2.0
4         1.0
         ... 
299995    1.0
299996    2.0
299997    2.0
299998    5.0
299999    3.0
Name: quantity, Length: 300000, dtype: float64

In [ ]:
quantity_num.isna().sum()

np.int64(30147)

In [ ]:
quantity_num.value_counts(dropna=False).sort_index()

quantity
-3.0    14939
 0.0    14878
 1.0    44765
 2.0    60270
 3.0    45296
 4.0    45058
 5.0    44647
 NaN    30147
Name: count, dtype: int64

The Orders quantity attribute contains 30,147 records (10.05%) that cannot be interpreted as numeric quantities: 15,050 whitespace-only values and 15,097 textual "five" values. No actual NULL values were present in the raw attribute.

In [ ]:
orders_product = orders.merge(
    Products[["product_id", "price"]],
    on="product_id",
    how="left"
)

In [ ]:
orders_product["price_num"] = (
    orders_product["price"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .astype(float)
)


In [ ]:
orders_product["quantity_num"] = quantity_num

In [ ]:
orders_product["order_amount_num"] = (
    orders_product["order_amount"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [ ]:
orders_product[
    ["product_id", "quantity_num", "price_num", "order_amount_num"]
].head(20)

,product_id,quantity_num,price_num,order_amount_num
0,PROD-0060,1.0,16331.66,473.82
1,PROD-0393,1.0,14148.77,17796.32
2,PROD-0332,2.0,23041.73,31201.75
3,PROD-0059,2.0,18500.33,42282.89
4,PROD-0342,1.0,34607.69,27100.30
5,PROD-0297,4.0,24344.17,2393.67
6,PROD-0137,5.0,24839.33,12532.69
7,PROD-0010,2.0,0.00,47079.63
8,PROD-0243,5.0,3085.85,32901.99
9,PROD-0084,3.0,17910.72,3858.55


In [ ]:
orders_product['expected_amount'] = (
    orders_product['price_num'] *
    orders_product['quantity_num']
)

In [ ]:
valid_amount_inputs = (
    orders_product["quantity_num"].notna()
    & orders_product["price_num"].notna()
    & orders_product["order_amount_num"].notna()
)

In [ ]:
valid_amount_inputs.sum()

np.int64(244715)

In [ ]:
orders_product["expected_amount"] = (
    orders_product["quantity_num"] *
    orders_product["price_num"]
)

In [ ]:
amount_matchs = (
    orders_product['order_amount_num'].round(2)
    == orders_product['expected_amount'].round(2)
)

In [ ]:
amount_matchs.sum()

np.int64(1145)

In [ ]:
amount_matches = (
    orders_product.loc[valid_amount_inputs, "expected_amount"].round(2)
    ==
    orders_product.loc[valid_amount_inputs, "order_amount_num"].round(2)
)

In [ ]:
amount_matches.value_counts()

False    243570
True       1145
Name: count, dtype: int64

Observation: Among the 244,715 orders for which quantity, product price, and order amount were available, 243,570 (99.53%) did not satisfy the tested quantity × product_price = order_amount calculation, while 1,145 (0.47%) matched.

In [ ]:
orders_product.loc[
    valid_amount_inputs,
    ["product_id", "quantity_num", "price_num",
     "expected_amount", "order_amount_num"]
].head(20)

,product_id,quantity_num,price_num,expected_amount,order_amount_num
0,PROD-0060,1.0,16331.66,16331.66,473.82
1,PROD-0393,1.0,14148.77,14148.77,17796.32
2,PROD-0332,2.0,23041.73,46083.46,31201.75
3,PROD-0059,2.0,18500.33,37000.66,42282.89
4,PROD-0342,1.0,34607.69,34607.69,27100.30
5,PROD-0297,4.0,24344.17,97376.68,2393.67
6,PROD-0137,5.0,24839.33,124196.65,12532.69
7,PROD-0010,2.0,0.00,0.00,47079.63
8,PROD-0243,5.0,3085.85,15429.25,32901.99
9,PROD-0084,3.0,17910.72,53732.16,3858.55


In [ ]:
orders_product["amount_difference"] = (
    orders_product["order_amount_num"]
    - orders_product["expected_amount"]
)

In [ ]:
price_nonzero = (
    valid_amount_inputs
    & orders_product["price_num"].ne(0)
)

In [ ]:
amount_price_ratio = (
    orders_product.loc[price_nonzero, "order_amount_num"]
    /
    orders_product.loc[price_nonzero, "price_num"]
)

In [ ]:
amount_price_ratio.describe()

count    234963.000000
mean        -17.818866
std         323.579506
min       -9977.011800
25%           0.168304
50%           0.837823
75%           2.138701
max        9264.437367
dtype: float64

## Observation — Quantity × Product Price × Order Amount

Among **244,715 orders with sufficient numeric inputs**, only **1,145 orders (0.47%)** matched the calculated `quantity × product_price`, while **243,570 orders (99.53%)** did not.

This indicates that the tested relationship `quantity × product_price = order_amount` does not hold for the majority of evaluable orders. However, the mismatch cannot yet be conclusively classified as a **Data Quality defect**, because the intended business calculation for `order_amount` has not been established and additional anomalies exist in `quantity`, `product_price`, and `order_amount`.

**Conclusion:** The relationship is a significant profiling observation requiring business-rule confirmation, rather than a confirmed DQ defect.

## Objective — CRM ↔ Support Tickets Cross-Table Profiling

Assess the relationship between **CRM customers and Support Tickets** to determine whether ticket records can be reliably associated with CRM customer identities.

The investigation will examine **customer ID coverage, unmatched customer references, duplicate CRM identities, and relationship consistency** to identify potential Customer 360 integration and Data Quality risks.

In [ ]:
support_ticket['ticket_id'].count()

np.int64(30000)

In [ ]:
support_ticket['ticket_id'].nunique()

30000

In [ ]:
support_ticket['ticket_id'].isna().sum()

np.int64(0)

ticket_id is a strong candidate key for the Support Ticket table because it has 30,000 distinct values across 30,000 records and contains no NULL values.

In [ ]:
# check whether ticket_id contains blank/whitespace values

support_ticket.loc[
    support_ticket['ticket_id'].astype(str).str.strip().eq(""),
    'ticket_id'
].value_counts(dropna=False).sort_values()

Series([], Name: count, dtype: int64)

the result is 0, we have stronger evidence that ticket_id is a valid candidate key.

Are there orphan support tickets — tickets whose customer_id does not exist in CRM?

In [ ]:
support_ticket['customer_id'].isin(crm['customer_id']).sum()

np.int64(30000)

No orphan customer references were detected between Support Tickets and CRM based on exact customer_id matching.

In [ ]:
support_ticket["customer_id"].nunique()

22149

there are 22149 distinct customer present in the support ticket dataset, but we don't know how many customer have more the on ticket. Need further investigation.

In [ ]:
support_ticket['customer_id'].value_counts()

customer_id
8e387f7c-a674-4039-8994-998a6b59e14e    6
0d3de1ba-c9cf-4a24-b381-e9863beb41d3    6
ac66a771-49b4-4aac-837b-9e7321e90daf    6
38207b10-1611-4ce8-82e2-bc3c432f7521    6
7dbc4c01-aafa-4752-b279-9dd95e21efcb    6
                                       ..
4467762f-01b9-46eb-91e9-daab3a7a2312    1
539768a9-a8d6-44f3-8fd0-5db7b69bfe06    1
8cac7dc3-72bc-4f3a-89d4-fd0f5bb59c8b    1
66c10216-8f35-4cb6-8cc1-a57d3c785ed9    1
46a03eec-cfc6-42e1-96d1-8df25ce1b03a    1
Name: count, Length: 22149, dtype: int64

In [ ]:
support_ticket['customer_id'].value_counts().value_counts()

count
1    15886
2     4950
3     1083
4      192
5       31
6        7
Name: count, dtype: int64

All 30,000 support-ticket customer references were found in CRM, so no orphan customer references were detected based on exact customer_id matching. The Support dataset represents 22,149 distinct CRM customers, with ticket frequency ranging from 1 to 6 tickets per customer.

## Observation — CRM ↔ Support Tickets

The Support Tickets dataset contains **30,000 tickets** associated with **22,149 distinct customer IDs**. This indicates that some customers have multiple support tickets, with **7,851 ticket records beyond the first ticket per distinct customer**.

The **22,149 figure represents distinct customers with at least one ticket**, not the number of customers with multiple tickets. The presence of multiple tickets per customer is therefore a relationship characteristic and is not, by itself, a Data Quality defect.

The CRM-to-Support relationship should be assessed primarily based on **customer ID matchability and unmatched references** before determining whether any identity-related Data Quality issue exists.

## Objective — CRM ↔ Clickstream Cross-Table Profiling

Assess the relationship between **CRM customers and Clickstream activity** to determine whether customer identities can be reliably linked across the two datasets.

The investigation will examine **customer ID coverage, unmatched references, distinct customer participation, and relationship patterns** to identify potential Customer 360 integration and Data Quality risks.

In [ ]:
clickstream.columns

Index(['event_id', 'session_id', 'customer_id', 'event_type', 'page_url',
       'device_id', 'timestamp', 'ingest_run_id'],
      dtype='str')

In [ ]:
clickstream['event_id'].count()

np.int64(500000)

In [ ]:
clickstream['event_id'].nunique()

500000

In [ ]:
clickstream['event_id'].isna().sum()

np.int64(0)

In [ ]:
clickstream.loc[
    clickstream['event_id'].astype(str).str.strip().eq(''),
    'event_id'
].value_counts(dropna = False)

Series([], Name: count, dtype: int64)

event_id is a strong candidate key for the Clickstream dataset because every one of the 500,000 records has a distinct, non-null, non-blank event_id.

In [ ]:
crm_customer_ids = crm["customer_id"].unique()

clickstream["customer_id"].isin(crm_customer_ids).sum()

np.int64(349447)

Of the 500,000 clickstream events, 349,447 (69.89%) reference customer IDs that exist in the CRM customer population, while 150,553 events (30.11%) do not have a matching CRM customer ID. This indicates a potential referential-integrity issue between Clickstream and CRM.

In [ ]:
unmatched_clickstream = clickstream[
    ~clickstream["customer_id"].isin(crm_customer_ids)
]

unmatched_clickstream["customer_id"].isna().sum()

np.int64(150553)

In [ ]:
unmatched_clickstream["customer_id"].astype(str).str.strip().eq("").sum()

np.int64(0)

150,553 clickstream events (30.11% of the clickstream population) have NULL customer_id values. The remaining 349,447 events have customer IDs that successfully match the CRM customer population. No populated-but-unmatched customer IDs were detected.

## Observation — CRM ↔ Clickstream

The Clickstream dataset contains **500,000 events**, of which **349,447 events (69.89%)** have a `customer_id` that successfully matches a CRM customer.

The remaining **150,553 events (30.11%)** contain `NULL` `customer_id` values, while **no populated-but-unmatched customer IDs** were identified.

Therefore, no orphan customer references were observed in the Clickstream-to-CRM relationship. The business acceptability of the **30.11% NULL population** requires further confirmation based on Clickstream event types and business rules.

## Objective — Anomaly Detection

Identify unusual or unexpected patterns in the profiled data that may require further Data Quality investigation.

The analysis will focus on **statistical outliers, unusual distributions, extreme values, and unexpected record patterns**, while distinguishing genuine anomalies from valid business variation before classifying them as Data Quality issues.

In [ ]:
# Which customers have an unusually high number of orders?

orders['customer_id'].value_counts().describe()

count    48077.000000
mean         6.239990
std          2.732138
min          1.000000
25%          4.000000
50%          6.000000
75%          8.000000
max         30.000000
Name: count, dtype: float64

In [ ]:
order_counts = orders['customer_id'].value_counts()

In [ ]:
order_counts[order_counts >= 15].sort_values(ascending= False)

customer_id
663ea09b-0231-4c3a-9965-6b1a0a1f3b07    30
e6864b1c-c022-4735-9b49-5b7146b5d24a    28
75193cbb-8f90-4ae7-86bd-5d4aa095595d    27
ca15911c-c86d-4fd9-adb7-5f77ff5fb79a    27
20cc2caa-51ab-406b-af31-16ebc97ccafc    26
                                        ..
9672400b-c1cf-463f-ad24-f50326684236    15
95927fec-9dec-47e2-87ce-6e382909f127    15
232c8c5c-ce21-4547-935d-cb5ea749498e    15
e14cc69c-cae3-4add-bda1-333815da498d    15
735f5291-ea0e-49bf-b667-f5c567763e56    15
Name: count, Length: 478, dtype: int64

In [ ]:
order_counts[order_counts == 30].index

Index(['663ea09b-0231-4c3a-9965-6b1a0a1f3b07'], dtype='str', name='customer_id')

In [ ]:
high_order_customer = order_counts[order_counts == 30].index[0]

orders[orders['customer_id'] == high_order_customer]


,order_id,customer_id,product_id,order_amount,order_date,payment_method,status,quantity,amount_sign
35767,c26af4f8-8d41-4f53-8c1c-bcb679e4c75b,663ea09b-0231-4c3a-9965-6b1a0a1f3b07,PROD-0159,17433.94,2025-04-25,cd,success,,non_negative
39571,d8d36408-c95b-4578-bb69-682e143e718d,663ea09b-0231-4c3a-9965-6b1a0a1f3b07,PROD-0061,5274.09,2024/31/01,CRAD,SUCCESS,4,non_negative
50308,d7f9ff94-0f5b-4a2e-9484-ac3503c38126,663ea09b-0231-4c3a-9965-6b1a0a1f3b07,PROD-0467,0,2024-07-21,card,success,4,non_negative
51779,83ec075e-823e-4de3-88f4-712653bdbf0d,663ea09b-0231-4c3a-9965-6b1a0a1f3b07,PROD-0492,17511.48,2024-01-29,card,Success,,non_negative
76653,20b8d253-1e35-4e0a-89b5-9bfc5689560d,663ea09b-0231-4c3a-9965-6b1a0a1f3b07,PROD-0117,21459.11,2024-05-25,cash,success,4,non_negative
78407,d2e7597a-e03e-4d27-a9c9-828a2a66fe8f,663ea09b-0231-4c3a-9965-6b1a0a1f3b07,PROD-0069,48570.87,2026-09-13T15:17:59.810744,upi,Success,-3,non_negative
80232,9336036e-7c6f-403c-8d3f-fefdd2b14b05,663ea09b-0231-4c3a-9965-6b1a0a1f3b07,PROD-0400,43035.22,2025-11-18,upi,Success,5,non_negative
83501,34dbbabd-57e8-459d-b788-5e1b48d276a0,663ea09b-0231-4c3a-9965-6b1a0a1f3b07,PROD-0029,496715.92,2025-03-06,upi,success,4,non_negative
92054,abff50da-5a0c-4cd3-97fa-7b1b3681f756,663ea09b-0231-4c3a-9965-6b1a0a1f3b07,PROD-0447,41145.85,2024-07-10,upi,fail,-3,non_negative
96802,042a6287-9a45-438a-a6f5-543bdddbe3ce,663ea09b-0231-4c3a-9965-6b1a0a1f3b07,PROD-0368,28429.37,2024-01-05,cash,SUCCESS,1,non_negative


Observation: One CRM customer is associated with 30 orders, compared with a median of 6 orders per customer and a maximum of 30.
Investigation: The customer's orders contain distinct order IDs, multiple products, varying amounts, dates, payment methods, and statuses. No obvious duplicate-order pattern was identified from the inspected records.
Conclusion: The high order frequency is an anomaly candidate, but there is currently insufficient evidence to classify it as a Data Quality defect.
Disposition: No DQ issue raised at this stage.

In [ ]:
# Are there products with unusually high transaction frequency?

product_order_counts = orders['product_id'].value_counts()

product_order_counts.describe()

count    500.000000
mean     600.000000
std       25.033124
min      515.000000
25%      584.000000
50%      599.000000
75%      617.000000
max      677.000000
Name: count, dtype: float64

Observation: Transaction frequency across the 500 products ranges from 515 to 677 orders per product, with a median of 599 and standard deviation of approximately 25. The distribution is relatively concentrated, with no product exhibiting an extreme transaction-frequency deviation based on this profiling.

## Objective

Assess whether zero `quantity` values are distributed differently across order `status` categories, to identify potential relationships between quantity validity and order status.

In [ ]:
pd.crosstab(
    orders["status"],
    orders["quantity_num"].eq(0)
)

KeyError: 'quantity_num'

In [ ]:
pd.crosstab(
    negative_orders["status"],
    negative_orders["quantity"].eq(0)
)

quantity,False
status,
failed,1505
refund,1313
success,9441


In [1326]:
orders_product

,order_id,customer_id,product_id,order_amount,order_date,payment_method,status,quantity,amount_sign,price,price_num,order_amount_num
0,06b5aa88-f86f-4e07-8e4b-6df36402c209,0a331d4c-a73d-4271-83ac-2f6726635495,PROD-0060,473.82,2025-07-29,wall-et,success,1,non_negative,16331.66,16331.66,473.82
1,5b10b856-e084-471c-bc16-8dbab95e3f33,9e48263f-7923-4cb9-8138-b9da8eb85619,PROD-0393,17796.32,2024/31/01,card,success,1,non_negative,14148.77,14148.77,17796.32
2,88706122-160e-4721-b537-73cee232fcd5,245fac1f-5ac1-4448-acc9-70ff980a4e9b,PROD-0332,31201.75,2024-03-02,wallet,success,2,non_negative,23041.73,23041.73,31201.75
3,c6ae75af-0313-4194-a788-8802515af2e4,abfda25e-6a38-4aa8-be24-cd22f371b2b0,PROD-0059,42282.89,NaN,wallet,refunded,2,non_negative,18500.33,18500.33,42282.89
4,032ab1c7-8882-47d8-a2ac-fbefc1cfb2eb,e0010492-b072-4f48-abd6-8a87938fad24,PROD-0342,27100.3,2024-02-11,wallet,success,1,non_negative,34607.69,34607.69,27100.30
...,...,...,...,...,...,...,...,...,...,...,...,...
299995,961d6ef1-e747-457d-804b-d534831caa5a,e3a4d1b9-27ee-4a4a-8b69-4070e9f014ce,PROD-0147,46224.46,31-12-2023,wallet,success,1,non_negative,45160.61,45160.61,46224.46
299996,556d5b5d-a7f6-478d-91dd-0ca0bc774d33,c4e8e517-75e1-4de3-8cc4-59b82005cd73,PROD-0480,3375.16,2025-06-26,cash,success,2,non_negative,-100,-100.00,3375.16
299997,411acb70-4f84-46e9-a60b-78ed74456a5c,5129d935-2ea3-46be-b4db-110a38ee7665,PROD-0364,"1,200",2025-02-10,CRAD,SUCCESS,2,non_negative,46898.45,46898.45,1200.00
299998,60fa25a6-439c-4a2a-a214-3fc0a3f11977,8d21c4fc-082e-4e7e-b377-a6611d2542d0,PROD-0177,13043.39,2025-10-28,cash,success,5,non_negative,-100,-100.00,13043.39
